export const restaurants = [
	{
		id: 1,
		slug: 'qazaq-gourmet',
		title: 'Qazaq Gourmet',
		city: 'Astana',
		cuisine: 'Казахская кухня',
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: 'проспект Мангилик Ел, 29',
		image: '/imgs/usefulls/qazaq-gourmet.png',
		description:
			'Qazaq Gourmet — это первый ресторан высокой казахской кухни в Астане, вдохновлённый традициями и современными гастрономическими техниками.',
		buttonText: 'Подробнее',
		link: '/restaurants/qazaq-gourmet',
	},
	{
		id: 2,
		slug: 'daididau',
		title: 'Daididau',
		city: 'Astana',
		cuisine: 'Казахская кухня',
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: 'проспект Мангилик Ел, 29',
		image: '/imgs/usefulls/daididau.png',
		description: 'Daididau — атмосферный ресторан с акцентом на национальные блюда, живую музыку и уютный интерьер.',
		buttonText: 'Подробнее',
		link: '/restaurants/daididau',
	},
	{
		id: 3,
		slug: 'sandyk',
		title: 'Sandyk',
		city: 'Astana',
		cuisine: 'Казахская кухня',
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: 'улица Сарайшык, 3/4',
		image: '/imgs/usefulls/sandyk.png',
		description: 'Sandyk — ресторан с этническим интерьером и аутентичной кухней, передающей дух казахского наследия.',
		buttonText: 'Подробнее',
		link: '/restaurants/sandyk',
	},
	{
		id: 4,
		slug: 'arnau',
		title: 'Arnau',
		city: 'Astana',
		cuisine: 'Авторская кухня',
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: 'улица Нажимеденова, 14, ЖК Highville Palace',
		image: '/imgs/usefulls/arnau.png',
		description: 'Arnau — ресторан современной авторской кухни, где традиционные вкусы сочетаются с изысканной подачей.',
		buttonText: 'Подробнее',
		link: '/restaurants/arnau',
	},
	{
		id: 5,
		slug: 'qazaq-gourmet-2',
		title: 'Qazaq Gourmet',
		city: 'Astana',
		cuisine: 'Казахская кухня',
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: 'проспект Мангилик Ел, 29',
		image: '/imgs/usefulls/qazaq-gourmet.png',
		description: 'Флагманский ресторан высокой казахской кухни с уникальным интерьером и гастрономическими сетами.',
		buttonText: 'Подробнее',
		link: '/restaurants/qazaq-gourmet',
	},
	{
		id: 6,
		slug: 'daididau-2',
		title: 'Daididau',
		city: 'Astana',
		cuisine: 'Казахская кухня',
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: 'проспект Мангилик Ел, 29',
		image: '/imgs/usefulls/daididau.png',
		description: 'Ресторан с уютной атмосферой, живыми выступлениями и классическими блюдами национальной кухни.',
		buttonText: 'Подробнее',
		link: '/restaurants/daididau',
	},
	{
		id: 7,
		slug: 'sandyk-2',
		title: 'Sandyk',
		city: 'Astana',
		cuisine: 'Казахская кухня',
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: 'улица Сарайшык, 3/4',
		image: '/imgs/usefulls/sandyk.png',
		description: 'Просторный зал, национальный декор и тщательно подобранное меню для ценителей традиционной кухни.',
		buttonText: 'Подробнее',
		link: '/restaurants/sandyk',
	},
	{
		id: 8,
		slug: 'arnau-2',
		title: 'Arnau',
		city: 'Astana',
		cuisine: 'Авторская кухня',
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: 'улица Нажимеденова, 14, ЖК Highville Palace',
		image: '/imgs/usefulls/arnau.png',
		description: 'Современный ресторан с акцентом на локальные продукты и авторский подход к каждому блюду.',
		buttonText: 'Подробнее',
		link: '/restaurants/arnau',
	},
]
