import { RestaurantItemMultilang, Locale } from './restaurant.types'

export const restaurantsMultilang: RestaurantItemMultilang[] = [
	{
		id: 1,
		slug: 'selfie',
		title: { ru: 'Selfie', kk: 'Selfie', en: 'Selfie' },
		city: 'Astana',
		cuisine: { ru: 'Высокая кухня', kk: 'Жоғары асхана', en: 'Fine dining' },
		rating: 5,
		price: 30000,
		currency: 'KZT',
		address: {
			ru: 'Улица Достык, 16, Ritz Carlton Astana, 18 этаж 24+',
			kk: 'Достық көшесі, 16, Ritz Carlton Astana, 18-қабат, 24+',
			en: 'Dostyk Street, 16, Ritz-Carlton Astana, 18th floor, 24+',
		},
		image: 'https://visitastana.kz/upload/iblock/65b/j6frldq5qdw9iy6w25lyj0brrrwn91qh.jpg',
		description: {
			ru: 'Selfie — панорамный ресторан авторской кухни в сердце Астаны на 18-м этаже Ritz-Carlton. Здесь кухня, винная карта и атмосфера сочетаются в ярком гастрономическом спектакле.',
			kk: 'Selfie — Ritz-Carlton қонақүйінің 18-қабатында, Астананың қақ ортасында орналасқан панорамалық авторлық асхана мейрамханасы. Мұнда ас, шарап картасы және атмосфера жарқын гастрономиялық көрініске ұштасады.',
			en: 'Selfie is a panoramic chef-driven restaurant in the heart of Astana on the 18th floor of the Ritz-Carlton. Cuisine, wine list, and atmosphere come together in a vivid гастрономиялық experience.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/selfievastane/',
	},
	{
		id: 2,
		slug: 'shate',
		title: { ru: 'Shate', kk: 'Shate', en: 'Shate' },
		city: 'Astana',
		cuisine: { ru: 'Высокая кухня', kk: 'Жоғары асхана', en: 'Fine dining' },
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: {
			ru: 'Проспект Мангилик Ел, 35а',
			kk: 'Мәңгілік Ел даңғылы, 35а',
			en: 'Mangilik El Avenue, 35A',
		},
		image: 'https://visitastana.kz/upload/iblock/e6e/bomsa7ya8qrfjqzyhytw85s91lfyoc8j.png',
		description: {
			ru: 'Shate — ресторан авторской европейской кухни и аутентичной казахской гастрономии. Мы соединяем современные техники с традиционными рецептами, создавая блюда со стилем, вкусом и уважением к корням.',
			kk: 'Shate — авторлық еуропалық асхана мен аутентті қазақ гастрономиясын ұсынатын мейрамхана. Біз заманауи техникаларды дәстүрлі рецептурамен үйлестіріп, стиль мен дәмі бар, тамырды құрметтейтін тағамдар жасаймыз.',
			en: 'Shate is a restaurant of modern European авторлық cuisine and authentic Kazakh gastronomy. Contemporary techniques meet traditional recipes to create dishes with style, flavor, and respect for roots.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/shate.astana/',
	},
	{
		id: 3,
		slug: 'na-kryshe',
		title: { ru: 'На крыше', kk: 'На крыше', en: 'Na Kryshe' },
		city: 'Astana',
		cuisine: { ru: 'Высокая кухня', kk: 'Жоғары асхана', en: 'Fine dining' },
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: {
			ru: 'Улица Кадыргали Жалайыри, 2',
			kk: 'Қадырғали Жалайыри көшесі, 2',
			en: 'Kadyrgali Zhalayyri Street, 2',
		},
		image: 'https://visitastana.kz/upload/iblock/612/7px1y7sy0lobxc6mn0gs7tpjh571oqmr.png',
		description: {
			ru: '«На крыше» — атмосферное пространство с панорамным видом на город для тех, кто любит красивые виды, свежий воздух и незабываемые вечера. Высота дарит закаты, огни города и особую романтику открытой крыши.',
			kk: '«На крыше» — қалаға панорамалық көрініс ашылатын атмосфералық орын. Мұнда әсем көрініс, таза ауа және ұмытылмас кештерді ұнататындар жиналады. Биіктік күн батуын, қала шамдарын және ашық шатырдың ерекше романтикасын сыйлайды.',
			en: '“Na Kryshe” is an atmospheric rooftop venue with panoramic city views—perfect for those who love fresh air and memorable evenings. The height brings sunsets, city lights, and the unique romance of an open roof.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/nakryshe.rest/',
	},
	{
		id: 4,
		slug: 'felice-astana',
		title: { ru: 'Felice', kk: 'Felice', en: 'Felice' },
		city: 'Astana',
		cuisine: { ru: 'Высокая кухня', kk: 'Жоғары асхана', en: 'Fine dining' },
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: {
			ru: 'Проспект Сарыарка, 1',
			kk: 'Сарыарқа даңғылы, 1',
			en: 'Saryarka Avenue, 1',
		},
		image: 'https://visitastana.kz/upload/iblock/06a/0bx1m20go5ju2f7n34mn0eb6drbqdj6y.png',
		description: {
			ru: 'Felice — изысканный ресторан в центре города, где кухня, атмосфера и сервис создают гармоничное пространство для гастрономических впечатлений. Современный интерьер в тёплых тонах, удобные зоны и уютные уголки дарят комфорт.',
			kk: 'Felice — қала орталығындағы талғампаз мейрамхана. Мұнда асхана, атмосфера және сервис гастрономиялық әсерге арналған үйлесімді кеңістік қалыптастырады. Жылы реңктегі заманауи интерьер, ыңғайлы аймақтар мен жайлы бұрыштар комфорт сыйлайды.',
			en: 'Felice is an elegant restaurant in the city center where cuisine, atmosphere, and service create a harmonious space for gastronomic experiences. A warm-toned modern interior and cozy zones ensure comfort.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/felice_astana/',
	},
	{
		id: 5,
		slug: 'qazaq-gourmet',
		title: { ru: 'Qazaq Gourmet', kk: 'Qazaq Gourmet', en: 'Qazaq Gourmet' },
		city: 'Astana',
		cuisine: { ru: 'Национальная кухня', kk: 'Ұлттық асхана', en: 'National cuisine' },
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: {
			ru: 'Проспект Мангилик Ел, 29',
			kk: 'Мәңгілік Ел даңғылы, 29',
			en: 'Mangilik El Avenue, 29',
		},
		image: 'https://visitastana.kz/upload/iblock/15b/vwxjxwebjw6swyf1m0jlluheaxxnn46j.JPG',
		description: {
			ru: 'Qazaq Gourmet — первый ресторан высокой казахской кухни в Астане, вошедший в международный список 50 Best Discovery. Здесь традиции сочетаются с авторским взглядом, а каждый визит становится культурным и кулинарным путешествием.',
			kk: 'Qazaq Gourmet — Астанадағы жоғары қазақ асханасының алғашқы рестораны және 50 Best Discovery халықаралық тізіміне енген. Мұнда дәстүр авторлық көзқараспен үйлесіп, әрбір келу мәдени әрі аспаздық сапарға айналады.',
			en: 'Qazaq Gourmet is Astana’s first fine Kazakh cuisine restaurant, featured in the international 50 Best Discovery list. Traditions meet a chef’s авторлық perspective, turning every visit into a cultural and culinary journey.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/qazaq.gourmet',
	},
	{
		id: 6,
		slug: 'arnau',
		title: { ru: 'Arnau', kk: 'Arnau', en: 'Arnau' },
		city: 'Astana',
		cuisine: { ru: 'Национальная кухня', kk: 'Ұлттық асхана', en: 'National cuisine' },
		rating: 5,
		price: 15000,
		currency: 'KZT',
		address: {
			ru: 'пр. Туран, 30, в здании Fitness Palace',
			kk: 'Тұран даңғылы, 30, Fitness Palace ғимаратында',
			en: 'Turan Avenue, 30, Fitness Palace building',
		},
		image: 'https://visitastana.kz/upload/iblock/694/h9efu040kqxb4yst47j3cd9we2l644jy.jpg',
		description: {
			ru: 'Концепция Arnau — высокая казахская национальная кухня: изысканная и по-домашнему вкусная. Модный интерьер с национальными мотивами и живая музыка на народных инструментах создают особенное настроение.',
			kk: 'Arnau тұжырымдамасы — жоғары қазақ ұлттық асханасы: талғампаз әрі үйдегідей дәмді. Ұлттық өрнектері бар сәнді интерьер және халық аспаптарындағы жанды музыка ерекше көңіл күй сыйлайды.',
			en: 'Arnau focuses on fine Kazakh national cuisine—refined yet home-style tasty. A stylish интерьер with national motifs and live folk instruments create a special atmosphere.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/arnau_rest?igsh=MThtYjU4cTJrbzVrbw==',
	},
	{
		id: 7,
		slug: 'rubai',
		title: { ru: 'Rubai', kk: 'Rubai', en: 'Rubai' },
		city: 'Astana',
		cuisine: { ru: 'Национальная кухня', kk: 'Ұлттық асхана', en: 'National cuisine' },
		rating: 5,
		price: 7000,
		currency: 'KZT',
		address: {
			ru: 'Проспект Туран, 29',
			kk: 'Тұран даңғылы, 29',
			en: 'Turan Avenue, 29',
		},
		image: 'https://visitastana.kz/upload/iblock/5c6/9bcltinrsuqzg1htxhlema7b4ckyjwja.png',
		description: {
			ru: 'Rubai — пространство восточной щедрости и современного вкуса, где каждая деталь продумана для наслаждения моментом. Меню объединяет ближневосточную и европейскую кухни, а утончённый интерьер создаёт уют и стиль.',
			kk: 'Rubai — шығыстың кең пейілі мен заманауи дәмі тоғысқан орын. Әрбір бөлшек сәттен ләззат алуға арналған. Мәзірде Таяу Шығыс пен еуропалық ас үйлеседі, ал нәзік интерьер жайлылық пен стиль береді.',
			en: 'Rubai is a space of Eastern generosity and modern taste, where every detail is designed to enjoy the moment. The menu blends Middle Eastern and European cuisine, while the refined interior feels cozy and stylish.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/rubai.restaurant/',
	},
	{
		id: 8,
		slug: 'aula',
		title: { ru: 'Aula', kk: 'Aula', en: 'Aula' },
		city: 'Astana',
		cuisine: { ru: 'Национальная кухня', kk: 'Ұлттық асхана', en: 'National cuisine' },
		rating: 5,
		price: 5000,
		currency: 'KZT',
		address: {
			ru: 'Улица Сарайшык, 8',
			kk: 'Сарайшық көшесі, 8',
			en: 'Sarayshyk Street, 8',
		},
		image: 'https://visitastana.kz/upload/iblock/268/b60shyzlnthzb5vl9ljmy1it1tficyxa.png',
		description: {
			ru: 'Aula — уютный ресторан казахской и восточной кухни, где традиции и современность соединяются в одном пространстве. Гостей ждут аутентичные блюда по старинным рецептам с современными гастрономическими акцентами.',
			kk: 'Aula — қазақ және шығыс асханасының жайлы мейрамханасы. Мұнда дәстүр мен заманауилық бір кеңістікте тоғысады. Қонақтарды көне рецепттермен дайындалған аутентті тағамдар және заманауи гастро-акценттер күтеді.',
			en: 'Aula is a cozy Kazakh and Eastern restaurant where tradition meets modernity. Expect authentic dishes based on old recipes with contemporary gastronomic touches.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/aula_ast/',
	},
	{
		id: 9,
		slug: 'sirne',
		title: { ru: 'Sirne', kk: 'Sirne', en: 'Sirne' },
		city: 'Astana',
		cuisine: { ru: 'Национальная кухня', kk: 'Ұлттық асхана', en: 'National cuisine' },
		rating: 5,
		price: 5000,
		currency: 'KZT',
		address: {
			ru: 'Улица Ахмет Байтурсынулы, 18',
			kk: 'Ахмет Байтурсынұлы көшесі, 18',
			en: 'Akhmet Baitursynuly Street, 18',
		},
		image: 'https://visitastana.kz/upload/iblock/d86/eg195jroyvkid4c1do37eosebn1jlow9.PNG',
		description: {
			ru: 'Sirne — ресторан национальной и восточной кухни, где казахские вкусы сочетаются с яркими восточными мотивами. В меню — мясные блюда, плов и свежие лепешки из тандыра. Отлично подходит для неспешного обеда или уютного ужина.',
			kk: 'Sirne — ұлттық және шығыс асханасын ұсынатын мейрамхана. Мұнда қазақтың дәстүрлі дәмдері шығыстың жарқын нақыштарымен үйлеседі. Мәзірде — ет тағамдары, палау және тандырдан жаңа піскен нан. Асықпай түскі асқа да, жайлы кешкі асқа да ыңғайлы.',
			en: 'Sirne serves national and Eastern cuisine, blending classic Kazakh flavors with bold Eastern notes. The menu features hearty мяс dishes, pilaf, and fresh tandoor flatbreads—ideal for a relaxed lunch or a cozy dinner.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/sirne_restaurant/',
	},
	{
		id: 10,
		slug: 'bauyrdaq',
		title: { ru: 'Bauyrdaq', kk: 'Bauyrdaq', en: 'Bauyrdaq' },
		city: 'Astana',
		cuisine: { ru: 'Национальная кухня', kk: 'Ұлттық асхана', en: 'National cuisine' },
		rating: 5,
		price: 2000,
		currency: 'KZT',
		address: {
			ru: 'Ул. Ш. Уалиханова 19',
			kk: 'Ш. Уәлиханов көшесі, 19',
			en: 'Sh. Ualikhanov Street, 19',
		},
		image: 'https://visitastana.kz/upload/iblock/26e/b3muiu54gvu4hxy1eo9lha0d3t8d92rl.png',
		description: {
			ru: 'Bauyrdaq — уютное кафе быстрого питания, где традиционные казахские вкусы встречаются с современным подходом. Здесь подают любимые мясные блюда, закуски и свежие лепешки по классическим рецептам — быстро, сытно и комфортно.',
			kk: 'Bauyrdaq — дәстүрлі қазақ дәмдері заманауи форматта ұсынылатын жайлы фастфуд-кафе. Мұнда сүйікті ет тағамдары, тіскебасарлар және классикалық рецептпен дайындалған жаңа піскен нан бар — тез әрі тойымды.',
			en: 'Bauyrdaq is a cozy fast-food café where traditional Kazakh flavors meet a modern approach. Enjoy popular meat dishes, snacks, and fresh flatbreads made with classic recipes—quick, filling, and comfortable.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/bauyrdaq_astana/',
	},
	{
		id: 11,
		slug: 'daididau',
		title: { ru: 'Daididau', kk: 'Daididau', en: 'Daididau' },
		city: 'Astana',
		cuisine: { ru: 'Национальная кухня', kk: 'Ұлттық асхана', en: 'National cuisine' },
		rating: 5,
		price: 15000,
		currency: 'KZT',
		address: {
			ru: 'ул. Динмухамед Қонаев, 14',
			kk: 'Дінмұхамед Қонаев көшесі, 14',
			en: 'Dinmukhamed Kunaev Street, 14',
		},
		image: 'https://visitastana.kz/upload/iblock/845/1hr6nddjiffhvygd3gpasy6eg7zsbhyl.png',
		description: {
			ru: 'Daididau — ресторан высокой казахской и авторской кухни в самом сердце Астаны, где традиции встречаются с современными гастрономическими решениями. Каждый визит — маленькое путешествие сквозь вкусы, историю и музыку Казахстана.',
			kk: 'Daididau — Астананың қақ ортасындағы жоғары қазақ және авторлық асхана мейрамханасы. Мұнда дәстүр заманауи гастрономиялық шешімдермен тоғысады. Әрбір келу — Қазақстанның дәмі, тарихы мен музыкасы арқылы шағын сапар.',
			en: 'Daididau is a fine Kazakh and chef-driven restaurant in the heart of Astana, where tradition meets modern gastronomy. Every visit feels like a small journey through the flavors, history, and music of Kazakhstan.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/daididau.restaurant',
	},
	{
		id: 12,
		slug: 'saksaul',
		title: { ru: 'Saksaul', kk: 'Saksaul', en: 'Saksaul' },
		city: 'Astana',
		cuisine: { ru: 'Национальная кухня', kk: 'Ұлттық асхана', en: 'National cuisine' },
		rating: 5,
		price: 10000,
		currency: 'KZT',
		address: {
			ru: 'Улица Достык, 5',
			kk: 'Достық көшесі, 5',
			en: 'Dostyk Street, 5',
		},
		image: 'https://visitastana.kz/upload/iblock/daa/nvbpoqpcyfhdleru11qe55hlg0nk3gtp.png',
		description: {
			ru: 'Ресторан национальной и восточной кухни, объединяющий казахские вкусы и восточные мотивы. Здесь подают мясные блюда, ароматный плов и лепешки из тандыра — для уютного обеда или ужина.',
			kk: 'Ұлттық және шығыс асханасының мейрамханасы: қазақ дәмдері мен шығыс нақыштары үйлеседі. Мұнда ет тағамдары, хош иісті палау және тандыр наны ұсынылады — жайлы түскі асқа немесе кешкі асқа арналған.',
			en: 'A national and Eastern cuisine restaurant blending Kazakh flavors with Eastern motifs. Expect hearty meat dishes, fragrant pilaf, and tandoor flatbreads in a cozy setting.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/saksaul_astana/?hl=ru',
	},
	{
		id: 13,
		slug: 'asakusa',
		title: { ru: 'Asakusa', kk: 'Asakusa', en: 'Asakusa' },
		city: 'Astana',
		cuisine: { ru: 'Высокая кухня', kk: 'Жоғары асхана', en: 'Fine dining' },
		rating: 5,
		price: 10000,
		currency: 'KZT',
		address: {
			ru: 'Проспект Кабанбай батыра, 1',
			kk: 'Қабанбай батыр даңғылы, 1',
			en: 'Kabanbay Batyr Avenue, 1',
		},
		image: 'https://visitastana.kz/upload/iblock/2df/ekar2wnzjk0cvr2h0tcs7sjqsq185kvn.png',
		description: {
			ru: 'Asakusa — ресторан современной японской кухни в самом центре Астаны.',
			kk: 'Asakusa — Астананың қақ орталығындағы заманауи жапон асханасының мейрамханасы.',
			en: 'Asakusa is a modern Japanese cuisine restaurant in the very center of Astana.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/asakusa.izakaya/',
	},
	{
		id: 14,
		slug: 'sandyq',
		title: { ru: 'Sandyq', kk: 'Sandyq', en: 'Sandyq' },
		city: 'Astana',
		cuisine: { ru: 'Национальная кухня', kk: 'Ұлттық асхана', en: 'National cuisine' },
		rating: 5,
		price: 10000,
		currency: 'KZT',
		address: {
			ru: 'Улица Сарайшык, 34/3',
			kk: 'Сарайшық көшесі, 34/3',
			en: 'Sarayshyk Street, 34/3',
		},
		image: 'https://visitastana.kz/upload/iblock/6fa/ovn8sd58ozzstb0e2czzg3ccd7p8xam1.jpg',
		description: {
			ru: 'Sandyq — восточный ресторан в Астане, сочетающий национальный колорит, гостеприимство и живую музыку. Каждая деталь погружает в атмосферу сказочного Востока.',
			kk: 'Sandyq — Астанадағы шығыс мейрамханасы: ұлттық нақыш, қонақжайлық және жанды музыка үйлеседі. Әрбір деталь ертегідей Шығыс атмосферасына жетелейді.',
			en: 'Sandyq is an Eastern restaurant in Astana combining national flavor, hospitality, and live music—every detail immerses you in a сказочный Eastern atmosphere.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/sandyq_restaurant',
	},
	{
		id: 15,
		slug: 'tary',
		title: { ru: 'Tary', kk: 'Tary', en: 'Tary' },
		city: 'Astana',
		cuisine: { ru: 'Кофейни и кондитерские', kk: 'Кофеханалар және кондитерлік', en: 'Cafés & pastry shops' },
		rating: 5,
		price: 7000,
		currency: 'KZT',
		address: {
			ru: 'Улица Акмешит, 1',
			kk: 'Ақмешіт көшесі, 1',
			en: 'Akmеshit Street, 1',
		},
		image: 'https://visitastana.kz/upload/iblock/49a/2it0bof97bppcaht7xlf4bo0p5n6aicl.png',
		description: {
			ru: 'Tary — стильное место, где современная кухня встречается с уютной атмосферой. Здесь можно насладиться авторскими блюдами, напитками и комфортом для встреч с друзьями или семейного отдыха.',
			kk: 'Tary — заманауи асхана мен жайлы атмосфера тоғысқан стильді орын. Мұнда авторлық тағамдардан, сусындардан ләззат алып, достармен немесе отбасымен кездесуге ыңғайлы комфорт табасыз.',
			en: 'Tary is a stylish spot where modern food meets a cozy atmosphere. Enjoy chef-inspired dishes, pleasant drinks, and a comfortable space for friends or family time.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/tary.coffee/',
	},
	{
		id: 16,
		slug: 'cantinetta-antinori',
		title: { ru: 'Cantinetta Antinori', kk: 'Cantinetta Antinori', en: 'Cantinetta Antinori' },
		city: 'Astana',
		cuisine: { ru: 'Итальянская кухня', kk: 'Итальян асханасы', en: 'Italian cuisine' },
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: {
			ru: 'Кадыргали Жалайыри, 4',
			kk: 'Қадырғали Жалайыри көшесі, 4',
			en: 'Kadyrgali Zhalayyri Street, 4',
		},
		image: 'https://visitastana.kz/upload/iblock/20e/w01f0swz4hmkajok4ijlr9u90t0kethl.jpg',
		description: {
			ru: 'Cantinetta Antinori — тосканский ресторан в самом сердце Астаны, расположенный в отеле The Veil. Уютная атмосфера, изысканное меню и винные традиции семьи Антинори создают исключительный гастрономический опыт.',
			kk: 'Cantinetta Antinori — Астананың қақ орталығындағы тоскандық мейрамхана, The Veil қонақүйінде орналасқан. Жайлы атмосфера, талғампаз мәзір және Антинори әулетінің шарап дәстүрі ерекше гастрономиялық тәжірибе сыйлайды.',
			en: 'Cantinetta Antinori is a Tuscan restaurant in the heart of Astana, located in The Veil hotel. A cozy atmosphere, refined menu, and the Antinori family wine tradition create an exceptional dining experience.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/cantinettaantinori_kz?igsh=N2pvaDRwenlyb24=',
	},
	{
		id: 17,
		slug: 'ocean-basket',
		title: { ru: 'Ocean Basket', kk: 'Ocean Basket', en: 'Ocean Basket' },
		city: 'Astana',
		cuisine: { ru: 'Мясо/рыба', kk: 'Ет/балық', en: 'Meat & seafood' },
		rating: 5,
		price: 7000,
		currency: 'KZT',
		address: {
			ru: 'Сарайшық, 7',
			kk: 'Сарайшық, 7',
			en: 'Sarayshyk, 7',
		},
		image: 'https://visitastana.kz/upload/iblock/245/raqumdjvkrtnz5ib2fbmo8mz15m5py73.jpeg',
		description: {
			ru: 'Ocean Basket — сеть ресторанов морепродуктов, пришедшая в Астану, чтобы подарить городу вкус океана. В меню — свежие платтеры, суши и фирменные блюда по доступным ценам в уютной атмосфере.',
			kk: 'Ocean Basket — Астанаға «мұхит дәмін» әкелген теңіз өнімдері мейрамханаларының желісі. Мәзірде — жаңа платтерлер, суши және қолжетімді бағамен ұсынылатын фирмалық тағамдар, ал атмосферасы жайлы.',
			en: 'Ocean Basket is a seafood restaurant chain that came to Astana to bring the taste of the ocean. Enjoy fresh platters, sushi, and signature dishes at affordable prices in a cozy atmosphere.',
		},
		buttonText: { ru: 'Подробнее', kk: 'Толығырақ', en: 'More' },
		link: 'https://www.instagram.com/oceanbasket.kz/',
	},
]

export function getRestaurants(locale: Locale = 'ru') {
	return restaurantsMultilang.map((restaurant) => ({
		id: restaurant.id,
		slug: restaurant.slug,
		rating: restaurant.rating,
		price: restaurant.price,
		currency: restaurant.currency,
		image: restaurant.image,
		description: restaurant.description[locale],
		link: restaurant.link,
		title: restaurant.title[locale],
		city: restaurant.city,
		address: restaurant.address[locale],
		cuisine: restaurant.cuisine[locale],
		buttonText: restaurant.buttonText[locale],
	}))
}
