import { RestaurantItemMultilang, Locale } from './restaurant.types'

export const restaurantsMultilang: RestaurantItemMultilang[] = [
	{
		id: 1,
		slug: 'qazaq-gourmet',
		title: {
			ru: 'Qazaq Gourmet',
			kk: 'Qazaq Gourmet',
			en: 'Qazaq Gourmet',
		},
		city: 'Astana',
		cuisine: {
			ru: 'Казахская кухня',
			kk: 'Қазақ асханасы',
			en: 'Kazakh cuisine',
		},
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: {
			ru: 'проспект Мангилик Ел, 29',
			kk: 'Мәңгілік Ел даңғылы, 29',
			en: 'Mangilik El Avenue, 29',
		},
		image: '/imgs/usefulls/qazaq-gourmet.png',
		description: {
			ru: 'Qazaq Gourmet — это первый ресторан высокой казахской кухни в Астане, вдохновлённый традициями и современными гастрономическими техниками.',
			kk: 'Qazaq Gourmet — Астанадағы жоғары қазақ асханасының алғашқы рестораны, дәстүрлер мен заманауи гастрономиялық техникаларға шабыттанған.',
			en: 'Qazaq Gourmet is the first high-end Kazakh cuisine restaurant in Astana, inspired by traditions and modern gastronomic techniques.',
		},
		buttonText: {
			ru: 'Подробнее',
			kk: 'Толығырақ',
			en: 'More',
		},
		link: '/restaurants/qazaq-gourmet',
	},
	{
		id: 2,
		slug: 'daididau',
		title: {
			ru: 'Daididau',
			kk: 'Daididau',
			en: 'Daididau',
		},
		city: 'Astana',
		cuisine: {
			ru: 'Казахская кухня',
			kk: 'Қазақ асханасы',
			en: 'Kazakh cuisine',
		},
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: {
			ru: 'проспект Мангилик Ел, 29',
			kk: 'Мәңгілік Ел даңғылы, 29',
			en: 'Mangilik El Avenue, 29',
		},
		image: '/imgs/usefulls/daididau.png',
		description: {
			ru: 'Daididau — атмосферный ресторан с акцентом на национальные блюда, живую музыку и уютный интерьер.',
			kk: 'Daididau — ұлттық тағамдарға, тірі музыкаға және жайлы интерьерге назар аударатын атмосфералық ресторан.',
			en: 'Daididau is an atmospheric restaurant with a focus on national dishes, live music and a cozy interior.',
		},
		buttonText: {
			ru: 'Подробнее',
			kk: 'Толығырақ',
			en: 'More',
		},
		link: '/restaurants/daididau',
	},
	{
		id: 3,
		slug: 'sandyk',
		title: {
			ru: 'Sandyk',
			kk: 'Sandyk',
			en: 'Sandyk',
		},
		city: 'Astana',
		cuisine: {
			ru: 'Казахская кухня',
			kk: 'Қазақ асханасы',
			en: 'Kazakh cuisine',
		},
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: {
			ru: 'улица Сарайшык, 3/4',
			kk: 'Сарайшық көшесі, 3/4',
			en: 'Sarayshyk Street, 3/4',
		},
		image: '/imgs/usefulls/sandyk.png',
		description: {
			ru: 'Sandyk — ресторан с этническим интерьером и аутентичной кухней, передающей дух казахского наследия.',
			kk: 'Sandyk — этникалық интерьері мен қазақ мұрасының рухын беретін аутентикалық асханасы бар ресторан.',
			en: 'Sandyk is a restaurant with an ethnic interior and authentic cuisine that conveys the spirit of Kazakh heritage.',
		},
		buttonText: {
			ru: 'Подробнее',
			kk: 'Толығырақ',
			en: 'More',
		},
		link: '/restaurants/sandyk',
	},
	{
		id: 4,
		slug: 'arnau',
		title: {
			ru: 'Arnau',
			kk: 'Arnau',
			en: 'Arnau',
		},
		city: 'Astana',
		cuisine: {
			ru: 'Авторская кухня',
			kk: 'Авторлық асхана',
			en: 'Author cuisine',
		},
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: {
			ru: 'улица Нажимеденова, 14, ЖК Highville Palace',
			kk: 'Нажымеденов көшесі, 14, Highville Palace ТҚ',
			en: 'Nazhimedenov Street, 14, Highville Palace Residential Complex',
		},
		image: '/imgs/usefulls/arnau.png',
		description: {
			ru: 'Arnau — ресторан современной авторской кухни, где традиционные вкусы сочетаются с изысканной подачей.',
			kk: 'Arnau — дәстүрлі дәмдер таңдаулы ұсыныспен үйлесетін заманауи авторлық асхана рестораны.',
			en: 'Arnau is a restaurant of modern author cuisine, where traditional flavors are combined with exquisite presentation.',
		},
		buttonText: {
			ru: 'Подробнее',
			kk: 'Толығырақ',
			en: 'More',
		},
		link: '/restaurants/arnau',
	},
	{
		id: 5,
		slug: 'qazaq-gourmet-2',
		title: {
			ru: 'Qazaq Gourmet',
			kk: 'Qazaq Gourmet',
			en: 'Qazaq Gourmet',
		},
		city: 'Astana',
		cuisine: {
			ru: 'Казахская кухня',
			kk: 'Қазақ асханасы',
			en: 'Kazakh cuisine',
		},
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: {
			ru: 'проспект Мангилик Ел, 29',
			kk: 'Мәңгілік Ел даңғылы, 29',
			en: 'Mangilik El Avenue, 29',
		},
		image: '/imgs/usefulls/qazaq-gourmet.png',
		description: {
			ru: 'Флагманский ресторан высокой казахской кухни с уникальным интерьером и гастрономическими сетами.',
			kk: 'Бірегей интерьері мен гастрономиялық сеттері бар жоғары қазақ асханасының флагмандық рестораны.',
			en: 'A flagship restaurant of high Kazakh cuisine with a unique interior and gastronomic sets.',
		},
		buttonText: {
			ru: 'Подробнее',
			kk: 'Толығырақ',
			en: 'More',
		},
		link: '/restaurants/qazaq-gourmet',
	},
	{
		id: 6,
		slug: 'daididau-2',
		title: {
			ru: 'Daididau',
			kk: 'Daididau',
			en: 'Daididau',
		},
		city: 'Astana',
		cuisine: {
			ru: 'Казахская кухня',
			kk: 'Қазақ асханасы',
			en: 'Kazakh cuisine',
		},
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: {
			ru: 'проспект Мангилик Ел, 29',
			kk: 'Мәңгілік Ел даңғылы, 29',
			en: 'Mangilik El Avenue, 29',
		},
		image: '/imgs/usefulls/daididau.png',
		description: {
			ru: 'Ресторан с уютной атмосферой, живыми выступлениями и классическими блюдами национальной кухни.',
			kk: 'Жайлы атмосферасы, тірі орындалулары және ұлттық асхананың классикалық тағамдары бар ресторан.',
			en: 'A restaurant with a cozy atmosphere, live performances and classic dishes of national cuisine.',
		},
		buttonText: {
			ru: 'Подробнее',
			kk: 'Толығырақ',
			en: 'More',
		},
		link: '/restaurants/daididau',
	},
	{
		id: 7,
		slug: 'sandyk-2',
		title: {
			ru: 'Sandyk',
			kk: 'Sandyk',
			en: 'Sandyk',
		},
		city: 'Astana',
		cuisine: {
			ru: 'Казахская кухня',
			kk: 'Қазақ асханасы',
			en: 'Kazakh cuisine',
		},
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: {
			ru: 'улица Сарайшык, 3/4',
			kk: 'Сарайшық көшесі, 3/4',
			en: 'Sarayshyk Street, 3/4',
		},
		image: '/imgs/usefulls/sandyk.png',
		description: {
			ru: 'Просторный зал, национальный декор и тщательно подобранное меню для ценителей традиционной кухни.',
			kk: 'Кең зал, ұлттық декор және дәстүрлі асхананы бағалаушылар үшін мұқият таңдалған мәзір.',
			en: 'A spacious hall, national decor and a carefully selected menu for connoisseurs of traditional cuisine.',
		},
		buttonText: {
			ru: 'Подробнее',
			kk: 'Толығырақ',
			en: 'More',
		},
		link: '/restaurants/sandyk',
	},
	{
		id: 8,
		slug: 'arnau-2',
		title: {
			ru: 'Arnau',
			kk: 'Arnau',
			en: 'Arnau',
		},
		city: 'Astana',
		cuisine: {
			ru: 'Авторская кухня',
			kk: 'Авторлық асхана',
			en: 'Author cuisine',
		},
		rating: 5,
		price: 20000,
		currency: 'KZT',
		address: {
			ru: 'улица Нажимеденова, 14, ЖК Highville Palace',
			kk: 'Нажымеденов көшесі, 14, Highville Palace ТҚ',
			en: 'Nazhimedenov Street, 14, Highville Palace Residential Complex',
		},
		image: '/imgs/usefulls/arnau.png',
		description: {
			ru: 'Современный ресторан с акцентом на локальные продукты и авторский подход к каждому блюду.',
			kk: 'Жергілікті өнімдерге назар аударатын және әр тағамға авторлық тәсілді қолданатын заманауи ресторан.',
			en: 'A modern restaurant with a focus on local products and an authorial approach to each dish.',
		},
		buttonText: {
			ru: 'Подробнее',
			kk: 'Толығырақ',
			en: 'More',
		},
		link: '/restaurants/arnau',
	},
]

export function getRestaurants(locale: Locale = 'ru') {
	return restaurantsMultilang.map((restaurant) => ({
		id: restaurant.id,
		slug: restaurant.slug,
		rating: restaurant.rating,
		price: restaurant.price,
		currency: restaurant.currency,
		image: restaurant.image,
		description: restaurant.description[locale],
		link: restaurant.link,
		title: restaurant.title[locale],
		city: restaurant.city,
		address: restaurant.address[locale],
		cuisine: restaurant.cuisine[locale],
		buttonText: restaurant.buttonText[locale],
	}))
}
