import type { GalleryDay } from './types'

export const galleryDaysMock: GalleryDay[] = [
	{
		key: '2026-04-22',
		label: { ru: '22 апреля', kk: '22 сәуір', en: 'Apr 22' },
		items: [
			{
				id: '1',
				image: '/imgs/gallery-3.png',
				title: 'Title 1',
				description: 'Description 1',
				alt: { ru: 'Фото 1', kk: 'Фото 1', en: 'Photo 1' },
			},
			{ id: '2', image: '/imgs/gallery-1.png', alt: { ru: 'Фото 2', kk: 'Фото 2', en: 'Photo 2' } },
			{
				id: '3',
				image: '/imgs/gallery-2.png',
				title: 'Title 3',
				description: 'Description 3',
				alt: { ru: 'Фото 3', kk: 'Фото 3', en: 'Photo 3' },
			},
			{
				id: '4',
				image: '/imgs/gallery-2.png',
				title: 'Title 4',
				description: 'Description 4',
				alt: { ru: 'Фото 4', kk: 'Фото 4', en: 'Photo 4' },
			},
			{
				id: '5',
				image: '/imgs/gallery-3.png',
				title: 'Title 5',
				description: 'Description 5',
				alt: { ru: 'Фото 5', kk: 'Фото 5', en: 'Photo 5' },
			},
			{
				id: '6',
				image: '/imgs/gallery-1.png',
				title: 'Title 6',
				description: 'Description 6',
				alt: { ru: 'Фото 6', kk: 'Фото 6', en: 'Photo 6' },
			},
			{ id: '7', image: '/imgs/gallery-3.png', alt: { ru: 'Фото 7', kk: 'Фото 7', en: 'Photo 7' } },
			{
				id: '8',
				image: '/imgs/gallery-2.png',
				title: 'Title 8',
				description: 'Description 8',
				alt: { ru: 'Фото 8', kk: 'Фото 8', en: 'Photo 8' },
			},
			{
				id: '9',
				image: '/imgs/gallery-1.png',
				title: 'Title 9',
				description: 'Description 9',
				alt: { ru: 'Фото 9', kk: 'Фото 9', en: 'Photo 9' },
			},
		],
	},
	{
		key: '2026-04-23',
		label: { ru: '23 апреля', kk: '23 сәуір', en: 'Apr 23' },
		items: [
			{
				id: '3',
				image: '/imgs/gallery-3.png',
				title: 'Title 3',
				description: 'Description 3',
				alt: { ru: 'Фото 3', kk: 'Фото 3', en: 'Photo 3' },
			},
			{
				id: '4',
				image: '/imgs/gallery-2.png',
				title: 'Title 4',
				description: 'Description 4',
				alt: { ru: 'Фото 4', kk: 'Фото 4', en: 'Photo 4' },
			},
			{
				id: '5',
				image: '/imgs/gallery-3.png',
				title: 'Title 5',
				description: 'Description 5',
				alt: { ru: 'Фото 5', kk: 'Фото 5', en: 'Photo 5' },
			},
			{
				id: '6',
				image: '/imgs/gallery-1.png',
				title: 'Title 6',
				description: 'Description 6',
				alt: { ru: 'Фото 6', kk: 'Фото 6', en: 'Photo 6' },
			},
			{
				id: '7',
				image: '/imgs/gallery-3.png',
				title: 'Title 7',
				description: 'Description 7',
				alt: { ru: 'Фото 7', kk: 'Фото 7', en: 'Photo 7' },
			},
			{
				id: '8',
				image: '/imgs/gallery-2.png',
				title: 'Title 8',
				description: 'Description 8',
				alt: { ru: 'Фото 8', kk: 'Фото 8', en: 'Photo 8' },
			},
			{
				id: '9',
				image: '/imgs/gallery-1.png',
				title: 'Title 9',
				description: 'Description 9',
				alt: { ru: 'Фото 9', kk: 'Фото 9', en: 'Photo 9' },
			},
		],
	},
]
