export const SLIDES_KZ = [
	{
		id: 11,
		image: '/imgs/flora-and-fauna/flora-and-fauna-11.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 12,
		image: '/imgs/flora-and-fauna/flora-and-fauna-12.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 2,
		image: '/imgs/flora-and-fauna/flora-and-fauna-2.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 4,
		image: '/imgs/flora-and-fauna/flora-and-fauna-4.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 8,
		image: '/imgs/flora-and-fauna/flora-and-fauna-8.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 9,
		image: '/imgs/flora-and-fauna/flora-and-fauna-9.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 10,
		image: '/imgs/flora-and-fauna/flora-and-fauna-10.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
]

export const SLIDES_UZ = [
	{
		id: 1,
		image: '/imgs/regions/uz/flora-and-fauna-1.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 2,
		image: '/imgs/regions/uz/flora-and-fauna-2.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 3,
		image: '/imgs/regions/uz/flora-and-fauna-3.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 4,
		image: '/imgs/regions/uz/flora-and-fauna-4.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 5,
		image: '/imgs/regions/uz/flora-and-fauna-5.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 6,
		image: '/imgs/regions/uz/flora-and-fauna-6.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 7,
		image: '/imgs/regions/uz/flora-and-fauna-7.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
]

export const SLIDES_TJ = [
	{
		id: 1,
		image: '/imgs/regions/tj/tj-ff-1.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога (Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan is characterized by a wide diversity of ecosystems, ranging from tugai riparian forests to alpine meadows. It is one of the most important habitats of the snow leopard. Other iconic species include the Pamir argali (Ovis ammon polii), the markhor (Capra falconeri heptneri), and the Siberian ibex (Capra sibirica alaiana Noack). The country’s flora includes more than 5,000 plant species, many of which are endemic wild ancestors of cultivated fruit crops.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 2,
		image: '/imgs/regions/tj/tj-ff-2.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога (Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan is characterized by a wide diversity of ecosystems, ranging from tugai riparian forests to alpine meadows. It is one of the most important habitats of the snow leopard. Other iconic species include the Pamir argali (Ovis ammon polii), the markhor (Capra falconeri heptneri), and the Siberian ibex (Capra sibirica alaiana Noack). The country’s flora includes more than 5,000 plant species, many of which are endemic wild ancestors of cultivated fruit crops.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 3,
		image: '/imgs/regions/tj/tj-ff-3.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога (Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan is characterized by a wide diversity of ecosystems, ranging from tugai riparian forests to alpine meadows. It is one of the most important habitats of the snow leopard. Other iconic species include the Pamir argali (Ovis ammon polii), the markhor (Capra falconeri heptneri), and the Siberian ibex (Capra sibirica alaiana Noack). The country’s flora includes more than 5,000 plant species, many of which are endemic wild ancestors of cultivated fruit crops.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 4,
		image: '/imgs/regions/tj/tj-ff-4.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога (Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan is characterized by a wide diversity of ecosystems, ranging from tugai riparian forests to alpine meadows. It is one of the most important habitats of the snow leopard. Other iconic species include the Pamir argali (Ovis ammon polii), the markhor (Capra falconeri heptneri), and the Siberian ibex (Capra sibirica alaiana Noack). The country’s flora includes more than 5,000 plant species, many of which are endemic wild ancestors of cultivated fruit crops.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 5,
		image: '/imgs/regions/tj/tj-ff-5.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога (Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan is characterized by a wide diversity of ecosystems, ranging from tugai riparian forests to alpine meadows. It is one of the most important habitats of the snow leopard. Other iconic species include the Pamir argali (Ovis ammon polii), the markhor (Capra falconeri heptneri), and the Siberian ibex (Capra sibirica alaiana Noack). The country’s flora includes more than 5,000 plant species, many of which are endemic wild ancestors of cultivated fruit crops.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 6,
		image: '/imgs/regions/tj/tj-ff-6.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога (Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan is characterized by a wide diversity of ecosystems, ranging from tugai riparian forests to alpine meadows. It is one of the most important habitats of the snow leopard. Other iconic species include the Pamir argali (Ovis ammon polii), the markhor (Capra falconeri heptneri), and the Siberian ibex (Capra sibirica alaiana Noack). The country’s flora includes more than 5,000 plant species, many of which are endemic wild ancestors of cultivated fruit crops.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 7,
		image: '/imgs/regions/tj/tj-ff-7.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога (Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan is characterized by a wide diversity of ecosystems, ranging from tugai riparian forests to alpine meadows. It is one of the most important habitats of the snow leopard. Other iconic species include the Pamir argali (Ovis ammon polii), the markhor (Capra falconeri heptneri), and the Siberian ibex (Capra sibirica alaiana Noack). The country’s flora includes more than 5,000 plant species, many of which are endemic wild ancestors of cultivated fruit crops.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 8,
		image: '/imgs/regions/tj/tj-ff-8.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога (Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan is characterized by a wide diversity of ecosystems, ranging from tugai riparian forests to alpine meadows. It is one of the most important habitats of the snow leopard. Other iconic species include the Pamir argali (Ovis ammon polii), the markhor (Capra falconeri heptneri), and the Siberian ibex (Capra sibirica alaiana Noack). The country’s flora includes more than 5,000 plant species, many of which are endemic wild ancestors of cultivated fruit crops.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
]
