export const SLIDES_KZ = [
	{
		id: 11,
		image: '/imgs/flora-and-fauna/flora-and-fauna-11.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 12,
		image: '/imgs/flora-and-fauna/flora-and-fauna-12.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 2,
		image: '/imgs/flora-and-fauna/flora-and-fauna-2.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 4,
		image: '/imgs/flora-and-fauna/flora-and-fauna-4.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 8,
		image: '/imgs/flora-and-fauna/flora-and-fauna-8.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 9,
		image: '/imgs/flora-and-fauna/flora-and-fauna-9.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 10,
		image: '/imgs/flora-and-fauna/flora-and-fauna-10.png',
		title: {
			kk: 'Қазақстанның флорасы мен фаунасы',
			ru: 'Флора и фауна Казахстана',
			en: 'The flora and fauna of Kazakhstan',
		},
		description: {
			kk: 'Қазақстанның флорасы мен фаунасы табиғи аумақтарының үлкендігіне байланысты өте алуан түрлі: далалар мен шөлдерден бастап Тянь-Шань мен Алтай тауларына дейін, онда ерекше түрлер бар, олардың көпшілігі Қызыл кітапқа енгізілген. Мұндай түрлерге қар барысы, Тянь-Шань қоңыр аюы, құлан, сондай-ақ қызғылт фламинго мен қарақұйрық жатады. \n\n Қазақстан аумағында 180-нен астам сүтқоректілер түрі, шамамен 500 құс түрі, сондай-ақ бауырымен жорғалаушылар, қосмекенділер мен балықтар тіршілік етеді. Өсімдіктер әлемі сексеуіл, арша, қарағай, қайың және көптеген дала шөптері мен гүлдерімен ерекшеленеді, бұл елдің биоәртүрлілігінің байлығын көрсетеді.',
			ru: 'Флора и фауна Казахстана чрезвычайно разнообразны благодаря крупным природным зонам: от степей и пустынь до гор Тянь-Шаня и Алтая, где встречаются уникальные виды, многие из которых занесены в Красную книгу. К числу таких видов относятся, в частности, снежный барс (ирбис), тяньшанский бурый медведь, кулан, а также розовые фламинго и джейраны. \n\n На территории страны обитает более 180 видов млекопитающих и около 500 видов птиц, а также многочисленные рептилии, амфибии и рыбы. Растительный мир представлен саксаулом, арчой, сосной, берёзой и разнообразными степными травами и цветами, что отражает богатство биоразнообразия страны.',
			en: 'Kazakhstan’s flora and fauna are highly diverse thanks to its vast range of landscapes—from steppes and deserts to the Tien Shan and Altai Mountains. The country is home to many unique species, including several listed in the Red Book, such as the snow leopard, the Tien Shan brown bear, and the kulan, as well as pink flamingos and gazelles. \n\n Kazakhstan hosts rich wildlife, with more than 180 mammal species and around 500 bird species, along with numerous reptiles, amphibians, and fish. Its vegetation includes saxaul in desert areas, as well as juniper, pine, birch, and a wide variety of steppe grasses and flowering plants, reflecting the country’s strong biodiversity.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
]

export const SLIDES_UZ = [
	{
		id: 1,
		image: '/imgs/regions/uz/flora-and-fauna-1.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 2,
		image: '/imgs/regions/uz/flora-and-fauna-2.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 3,
		image: '/imgs/regions/uz/flora-and-fauna-3.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 4,
		image: '/imgs/regions/uz/flora-and-fauna-4.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 5,
		image: '/imgs/regions/uz/flora-and-fauna-5.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 6,
		image: '/imgs/regions/uz/flora-and-fauna-6.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 7,
		image: '/imgs/regions/uz/flora-and-fauna-7.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Өзбекстанның жалпы биологиялық әртүрлілігі 27 000-нан астам түрді құрайды. Ел флорасында биік және биік өсімдіктер түрлері ерекшеленеді. Өзбекстан Республикасының аумағында шамамен 4500 жоғары өсімдіктер және 2000-нан астам саңырауқұлақ түрлері бар. Олардың ішінде 300-ден астамы сирек кездесетін және реликт түрлер болып табылады, олар мұқият қорғауды қажет етеді. Өзбекстан Республикасының Қызыл кітабына 314 өсімдік түрі енгізілген. Республикада жыл сайын жабайы дәрілік, тағамдық және техникалық өсімдіктердің шамамен 65 түрі өсіріледі. Ең көп өнім беретін түрлер: мия, ферула, каперс және итмұрын. Өзбекстанның фаунасына омыртқалылардың 715 түрі (107 сүтқоректілер, 467 құстар, 61 бауырымен жорғалаушылар, 3 қосмекенділер және 77 балықтар), сондай-ақ омыртқасыздардың 15 000-нан астам түрі кіреді. Өзбекстан Республикасының Қызыл кітабына 206 жануарлар түрі енгізілген. Соңғы он жылда қоршаған ортаны басқарудың күшеюінің нәтижесінде Өзбекстандағы көптеген жануарлар түрлері антропогендік әсерге ұшырады, олардың таралу аймағы мен популяциясы азайды, ал кейбіреулері толығымен жойылып кетті (азиялық гепард және тұран жолбарысы).',
			ru: 'Общее биологическое разнообразие Узбекистана составляет более 27 тысяч видов. Во флоре страны выделяются высокорослые и высшие виды растений. На территории Республики Узбекистан встречается около 4500 видов высших растений и более 2000 видов грибов. Среди них более 300 редких и реликтовых видов, нуждающихся в серьезной охране. 314 видов растений занесены в Красную книгу Республики Узбекистан. \n\n Ежегодно в республике выращивают около 65 видов дикорастущих лекарственных, пищевых и технических растений. Наибольшее количество урожаев приходится на следующие виды: солодка, ферула, каперсы, шиповник. \n\n В фауне Узбекистана насчитывается 715 видов позвоночных животных (млекопитающих – 107, птиц – 467, пресмыкающихся – 61, амфибий – 3 и рыб – 77), а также более 15 тысяч видов беспозвоночных. 206 видов животных занесены в Красную книгу Республики Узбекистан. В результате активизации природопользования за последние десять лет многие виды животных в Узбекистане подверглись сильному антропогенному влиянию, их ареалы и численность сократились, а некоторые полностью исчезли (Азиатский гепард, Туранский тигр).',
			en: "The total biological diversity of Uzbekistan comprises over 27,000 species. Tall and higher plant species stand out in the country's flora. There are approximately 4,500 species of higher plants and over 2,000 species of fungi on the territory of the Republic of Uzbekistan. Among them, over 300 are rare and relict species in need of serious protection. 314 plant species are listed in the Red Book of the Republic of Uzbekistan. About 65 species of wild medicinal, food, and industrial plants are grown in the republic annually. The following species produce the greatest number of harvests: licorice, ferula, capers, and rose hips. The fauna of Uzbekistan includes 715 species of vertebrates (107 mammals, 467 birds, 61 reptiles, 3 amphibians, and 77 fish), as well as over 15,000 species of invertebrates. 206 animal species are listed in the Red Data Book of the Republic of Uzbekistan. As a result of increased environmental management over the past ten years, many animal species in Uzbekistan have been subject to significant anthropogenic impacts, their ranges and populations have declined, and some have become completely extinct (the Asiatic cheetah and Turan tiger).",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
]

export const SLIDES_TJ = [
	{
		id: 1,
		image: '/imgs/regions/tj/tj-ff-1.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога(Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan boasts diverse ecosystems, from tugai forests to alpine meadows. It is a critical habitat for the elusive Snow Leopard. Other iconic species include the Marco Polo sheep (Ovis ammon polii), Markhor(Capra falconeri heptneri), and Siberian Ibex(Capra sibirica alaiana Noack). The flora includes over 5,000 plant species, many of which are endemic wild ancestors of fruit crops like apples and apricots.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 2,
		image: '/imgs/regions/tj/tj-ff-2.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога(Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan boasts diverse ecosystems, from tugai forests to alpine meadows. It is a critical habitat for the elusive Snow Leopard. Other iconic species include the Marco Polo sheep (Ovis ammon polii), Markhor(Capra falconeri heptneri), and Siberian Ibex(Capra sibirica alaiana Noack). The flora includes over 5,000 plant species, many of which are endemic wild ancestors of fruit crops like apples and apricots.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 3,
		image: '/imgs/regions/tj/tj-ff-3.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога(Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan boasts diverse ecosystems, from tugai forests to alpine meadows. It is a critical habitat for the elusive Snow Leopard. Other iconic species include the Marco Polo sheep (Ovis ammon polii), Markhor(Capra falconeri heptneri), and Siberian Ibex(Capra sibirica alaiana Noack). The flora includes over 5,000 plant species, many of which are endemic wild ancestors of fruit crops like apples and apricots.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 4,
		image: '/imgs/regions/tj/tj-ff-4.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога(Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan boasts diverse ecosystems, from tugai forests to alpine meadows. It is a critical habitat for the elusive Snow Leopard. Other iconic species include the Marco Polo sheep (Ovis ammon polii), Markhor(Capra falconeri heptneri), and Siberian Ibex(Capra sibirica alaiana Noack). The flora includes over 5,000 plant species, many of which are endemic wild ancestors of fruit crops like apples and apricots.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 5,
		image: '/imgs/regions/tj/tj-ff-5.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога(Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan boasts diverse ecosystems, from tugai forests to alpine meadows. It is a critical habitat for the elusive Snow Leopard. Other iconic species include the Marco Polo sheep (Ovis ammon polii), Markhor(Capra falconeri heptneri), and Siberian Ibex(Capra sibirica alaiana Noack). The flora includes over 5,000 plant species, many of which are endemic wild ancestors of fruit crops like apples and apricots.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 6,
		image: '/imgs/regions/tj/tj-ff-6.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога(Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan boasts diverse ecosystems, from tugai forests to alpine meadows. It is a critical habitat for the elusive Snow Leopard. Other iconic species include the Marco Polo sheep (Ovis ammon polii), Markhor(Capra falconeri heptneri), and Siberian Ibex(Capra sibirica alaiana Noack). The flora includes over 5,000 plant species, many of which are endemic wild ancestors of fruit crops like apples and apricots.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 7,
		image: '/imgs/regions/tj/tj-ff-7.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога(Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan boasts diverse ecosystems, from tugai forests to alpine meadows. It is a critical habitat for the elusive Snow Leopard. Other iconic species include the Marco Polo sheep (Ovis ammon polii), Markhor(Capra falconeri heptneri), and Siberian Ibex(Capra sibirica alaiana Noack). The flora includes over 5,000 plant species, many of which are endemic wild ancestors of fruit crops like apples and apricots.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 8,
		image: '/imgs/regions/tj/tj-ff-8.webp',
		title: {
			kk: 'Флорасы мен фаунасы',
			ru: 'Флора и фауна',
			en: 'The flora and fauna',
		},
		description: {
			kk: 'Тәжікстан экожүйелерінің алуан түрлілігімен ерекшеленеді: тоғайлы ормандардан альпілік шалғындарға дейін. Бұл ел қар барысының ең маңызды мекен ету аймақтарының бірі болып табылады. Басқа да айрықша түрлерге памирлік тау қошқары (Ovis ammon polii), бұрандалы мүйізді теке — мархур (Capra falconeri heptneri) және сібір текесі (Capra sibirica alaiana Noack) жатады. Ел флорасы 5000-нан астам өсімдік түрін қамтиды, олардың көпшілігі жеміс дақылдарының эндемик жабайы арғы тектері болып табылады.',
			ru: 'Таджикистан отличается разнообразием экосистем: от тугайных лесов до альпийских лугов. Это важнейший ареал обитания снежного барса. Другие знаковые виды включают памирского горного барана (Ovis ammon polii), винторогого козла (Capra falconeri heptneri) и сибирского козерога(Capra sibirica alaiana Noack). Флора насчитывает более 5000 видов, многие из которых являются эндемичными дикими предками фруктовых культур.',
			en: 'Tajikistan boasts diverse ecosystems, from tugai forests to alpine meadows. It is a critical habitat for the elusive Snow Leopard. Other iconic species include the Marco Polo sheep (Ovis ammon polii), Markhor(Capra falconeri heptneri), and Siberian Ibex(Capra sibirica alaiana Noack). The flora includes over 5,000 plant species, many of which are endemic wild ancestors of fruit crops like apples and apricots.',
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
]

export const SLIDES_KG = [
	{
		id: 1,
		image: '/imgs/regions/kg/kg-ff-1.webp',
		title: {
			kk: 'Қырғыз Республикасының флорасы мен фаунасы',
			ru: 'Флора и фауна Кыргызской Республики',
			en: 'Flora and fauna of the Kyrgyz Republic',
		},
		description: {
			kk: 'Қырғыз Республикасының табиғи әртүрлілігі таулы экожүйелердің басымдығы және табиғи аймақтардың кең спектрі арқылы қалыптасады - далалық және ормандықтан бастап субальпілік және альпілікке дейін. Республика Орталық Азияның биогеографиялық маңызды аймағында орналасқан және 3000-нан астам өсімдік түрлері мен шамамен 500 омыртқалы жануарлар түрлерінің мекені, соның ішінде қар барысы және Грейг лалагүлі сияқты сирек және эндемикалық түрлер. \n\n Қырғызстан әлемнің басымдық экоаймақтарының қатарына жатады және жаһандық «биоәртүрлілік ошақтарының» тізіміне кіреді. Планета аумағының тек 0,039% құрайтын аумақта әлемдік флораның шамамен 2% және әлемдік фаунаның 3%-дан астамы шоғырланған. \n\n Елде халықаралық маңызы бар үш сулы-батпақты жерлер, 11 маңызды орнитологиялық аумақтар және екі биосфералық қорық орналасқан. Қырғыз Республикасының Қызыл кітабына 57 құс түрі, 23 сүтқоректі түрі, 2 қосмекенді түрі, 8 бауырымен жорғалаушы түрі, 7 балық түрі, 18 буынаяқты түрі, сондай-ақ жойылу қаупі төнген 87 жоғары өсімдіктер мен саңырауқұлақтар түрі енгізілген. \n\n Соңғы онжылдықтарда бірқатар түрлердің санының азаюы және экожүйелердің жағдайының нашарлауы байқалды, бұл елдің биоәртүрлілігін сақтауда ерекше қорғалатын табиғи аумақтар жүйесінің негізгі рөлін атап көрсетеді. 2025 жылдың басына қарай Қырғызстанда 10 қорық, 13 ұлттық саябақ және 1,5 млн гектардан астам аумақты қамтитын ондаған заказниктер жұмыс істеп жатыр.',
			ru: 'Природное разнообразие Кыргызской Республики формируется за счёт преобладания горных экосистем и широкого спектра природных зон - от степных и лесных до субальпийских и альпийских. Республика расположена в биогеографически значимом регионе Центральной Азии и является местом обитания более 3 000 видов растений и около 500 видов позвоночных животных, включая редкие и эндемичные виды, такие как снежный барс и тюльпан Грейга. \n\n Кыргызстан относится к числу приоритетных экорегионов мира и входит в перечень глобальных «очагов биоразнообразия». На территории, составляющей лишь 0,039% площади планеты, сосредоточено около 2% мировой флоры и более 3% мировой фауны. \n\n В стране расположены три водно-болотных угодья международного значения, 11 важных орнитологических территорий и два биосферных заповедника. В Красную книгу Кыргызской Республики включены 57 видов птиц, 23 вида млекопитающих, 2 вида амфибий, 8 видов рептилий, 7 видов рыб, 18 видов членистоногих, а также 87 видов высших растений и грибов, находящихся под угрозой исчезновения. \n\n За последние десятилетия отмечается сокращение численности ряда видов и ухудшение состояния экосистем, что подчёркивает ключевую роль системы особо охраняемых природных территорий в сохранении биоразнообразия страны. На начало 2025 года в Кыргызстане функционируют 10 заповедников, 13 национальных парков и десятки заказников, охватывающие свыше 1,5 млн гектаров.',
			en: "The natural diversity of the Kyrgyz Republic is formed by the predominance of mountain ecosystems and a wide range of natural zones - from steppe and forest to subalpine and alpine. The republic is located in the biogeographically significant region of Central Asia and is home to more than 3,000 species of plants and about 500 species of vertebrates, including rare and endemic species such as the snow leopard and Greig's tulip.\n\n Kyrgyzstan is one of the world's priority ecoregions and is included in the list of global \"hotspots of biodiversity.\" About 2% of the world's flora and more than 3% of the world's fauna are concentrated in an area that makes up only 0.039% of the planet's surface. \n\n The country has three wetlands of international importance, 11 important ornithological areas, and two biosphere reserves. The Red Book of the Kyrgyz Republic includes 57 species of birds, 23 species of mammals, 2 species of amphibians, 8 species of reptiles, 7 species of fish, 18 species of arthropods, as well as 87 species of higher plants and fungi that are threatened with extinction. \n\n Over the past decades, there has been a decline in the number of a number of species and a deterioration in the state of ecosystems, which underscores the key role of the system of specially protected natural areas in preserving the country's biodiversity. As of early 2025, Kyrgyzstan has 10 nature reserves, 13 national parks, and dozens of wildlife sanctuaries covering over 1.5 million hectares.",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 2,
		image: '/imgs/regions/kg/kg-ff-2.webp',
		title: {
			kk: 'Қырғыз Республикасының флорасы мен фаунасы',
			ru: 'Флора и фауна Кыргызской Республики',
			en: 'Flora and fauna of the Kyrgyz Republic',
		},
		description: {
			kk: 'Қырғыз Республикасының табиғи әртүрлілігі таулы экожүйелердің басымдығы және табиғи аймақтардың кең спектрі арқылы қалыптасады - далалық және ормандықтан бастап субальпілік және альпілікке дейін. Республика Орталық Азияның биогеографиялық маңызды аймағында орналасқан және 3000-нан астам өсімдік түрлері мен шамамен 500 омыртқалы жануарлар түрлерінің мекені, соның ішінде қар барысы және Грейг лалагүлі сияқты сирек және эндемикалық түрлер. \n\n Қырғызстан әлемнің басымдық экоаймақтарының қатарына жатады және жаһандық «биоәртүрлілік ошақтарының» тізіміне кіреді. Планета аумағының тек 0,039% құрайтын аумақта әлемдік флораның шамамен 2% және әлемдік фаунаның 3%-дан астамы шоғырланған. \n\n Елде халықаралық маңызы бар үш сулы-батпақты жерлер, 11 маңызды орнитологиялық аумақтар және екі биосфералық қорық орналасқан. Қырғыз Республикасының Қызыл кітабына 57 құс түрі, 23 сүтқоректі түрі, 2 қосмекенді түрі, 8 бауырымен жорғалаушы түрі, 7 балық түрі, 18 буынаяқты түрі, сондай-ақ жойылу қаупі төнген 87 жоғары өсімдіктер мен саңырауқұлақтар түрі енгізілген. \n\n Соңғы онжылдықтарда бірқатар түрлердің санының азаюы және экожүйелердің жағдайының нашарлауы байқалды, бұл елдің биоәртүрлілігін сақтауда ерекше қорғалатын табиғи аумақтар жүйесінің негізгі рөлін атап көрсетеді. 2025 жылдың басына қарай Қырғызстанда 10 қорық, 13 ұлттық саябақ және 1,5 млн гектардан астам аумақты қамтитын ондаған заказниктер жұмыс істеп жатыр.',
			ru: 'Природное разнообразие Кыргызской Республики формируется за счёт преобладания горных экосистем и широкого спектра природных зон - от степных и лесных до субальпийских и альпийских. Республика расположена в биогеографически значимом регионе Центральной Азии и является местом обитания более 3 000 видов растений и около 500 видов позвоночных животных, включая редкие и эндемичные виды, такие как снежный барс и тюльпан Грейга. \n\n Кыргызстан относится к числу приоритетных экорегионов мира и входит в перечень глобальных «очагов биоразнообразия». На территории, составляющей лишь 0,039% площади планеты, сосредоточено около 2% мировой флоры и более 3% мировой фауны. \n\n В стране расположены три водно-болотных угодья международного значения, 11 важных орнитологических территорий и два биосферных заповедника. В Красную книгу Кыргызской Республики включены 57 видов птиц, 23 вида млекопитающих, 2 вида амфибий, 8 видов рептилий, 7 видов рыб, 18 видов членистоногих, а также 87 видов высших растений и грибов, находящихся под угрозой исчезновения. \n\n За последние десятилетия отмечается сокращение численности ряда видов и ухудшение состояния экосистем, что подчёркивает ключевую роль системы особо охраняемых природных территорий в сохранении биоразнообразия страны. На начало 2025 года в Кыргызстане функционируют 10 заповедников, 13 национальных парков и десятки заказников, охватывающие свыше 1,5 млн гектаров.',
			en: "The natural diversity of the Kyrgyz Republic is formed by the predominance of mountain ecosystems and a wide range of natural zones - from steppe and forest to subalpine and alpine. The republic is located in the biogeographically significant region of Central Asia and is home to more than 3,000 species of plants and about 500 species of vertebrates, including rare and endemic species such as the snow leopard and Greig's tulip.\n\n Kyrgyzstan is one of the world's priority ecoregions and is included in the list of global \"hotspots of biodiversity.\" About 2% of the world's flora and more than 3% of the world's fauna are concentrated in an area that makes up only 0.039% of the planet's surface. \n\n The country has three wetlands of international importance, 11 important ornithological areas, and two biosphere reserves. The Red Book of the Kyrgyz Republic includes 57 species of birds, 23 species of mammals, 2 species of amphibians, 8 species of reptiles, 7 species of fish, 18 species of arthropods, as well as 87 species of higher plants and fungi that are threatened with extinction. \n\n Over the past decades, there has been a decline in the number of a number of species and a deterioration in the state of ecosystems, which underscores the key role of the system of specially protected natural areas in preserving the country's biodiversity. As of early 2025, Kyrgyzstan has 10 nature reserves, 13 national parks, and dozens of wildlife sanctuaries covering over 1.5 million hectares.",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 3,
		image: '/imgs/regions/kg/kg-ff-3.webp',
		title: {
			kk: 'Қырғыз Республикасының флорасы мен фаунасы',
			ru: 'Флора и фауна Кыргызской Республики',
			en: 'Flora and fauna of the Kyrgyz Republic',
		},
		description: {
			kk: 'Қырғыз Республикасының табиғи әртүрлілігі таулы экожүйелердің басымдығы және табиғи аймақтардың кең спектрі арқылы қалыптасады - далалық және ормандықтан бастап субальпілік және альпілікке дейін. Республика Орталық Азияның биогеографиялық маңызды аймағында орналасқан және 3000-нан астам өсімдік түрлері мен шамамен 500 омыртқалы жануарлар түрлерінің мекені, соның ішінде қар барысы және Грейг лалагүлі сияқты сирек және эндемикалық түрлер. \n\n Қырғызстан әлемнің басымдық экоаймақтарының қатарына жатады және жаһандық «биоәртүрлілік ошақтарының» тізіміне кіреді. Планета аумағының тек 0,039% құрайтын аумақта әлемдік флораның шамамен 2% және әлемдік фаунаның 3%-дан астамы шоғырланған. \n\n Елде халықаралық маңызы бар үш сулы-батпақты жерлер, 11 маңызды орнитологиялық аумақтар және екі биосфералық қорық орналасқан. Қырғыз Республикасының Қызыл кітабына 57 құс түрі, 23 сүтқоректі түрі, 2 қосмекенді түрі, 8 бауырымен жорғалаушы түрі, 7 балық түрі, 18 буынаяқты түрі, сондай-ақ жойылу қаупі төнген 87 жоғары өсімдіктер мен саңырауқұлақтар түрі енгізілген. \n\n Соңғы онжылдықтарда бірқатар түрлердің санының азаюы және экожүйелердің жағдайының нашарлауы байқалды, бұл елдің биоәртүрлілігін сақтауда ерекше қорғалатын табиғи аумақтар жүйесінің негізгі рөлін атап көрсетеді. 2025 жылдың басына қарай Қырғызстанда 10 қорық, 13 ұлттық саябақ және 1,5 млн гектардан астам аумақты қамтитын ондаған заказниктер жұмыс істеп жатыр.',
			ru: 'Природное разнообразие Кыргызской Республики формируется за счёт преобладания горных экосистем и широкого спектра природных зон - от степных и лесных до субальпийских и альпийских. Республика расположена в биогеографически значимом регионе Центральной Азии и является местом обитания более 3 000 видов растений и около 500 видов позвоночных животных, включая редкие и эндемичные виды, такие как снежный барс и тюльпан Грейга. \n\n Кыргызстан относится к числу приоритетных экорегионов мира и входит в перечень глобальных «очагов биоразнообразия». На территории, составляющей лишь 0,039% площади планеты, сосредоточено около 2% мировой флоры и более 3% мировой фауны. \n\n В стране расположены три водно-болотных угодья международного значения, 11 важных орнитологических территорий и два биосферных заповедника. В Красную книгу Кыргызской Республики включены 57 видов птиц, 23 вида млекопитающих, 2 вида амфибий, 8 видов рептилий, 7 видов рыб, 18 видов членистоногих, а также 87 видов высших растений и грибов, находящихся под угрозой исчезновения. \n\n За последние десятилетия отмечается сокращение численности ряда видов и ухудшение состояния экосистем, что подчёркивает ключевую роль системы особо охраняемых природных территорий в сохранении биоразнообразия страны. На начало 2025 года в Кыргызстане функционируют 10 заповедников, 13 национальных парков и десятки заказников, охватывающие свыше 1,5 млн гектаров.',
			en: "The natural diversity of the Kyrgyz Republic is formed by the predominance of mountain ecosystems and a wide range of natural zones - from steppe and forest to subalpine and alpine. The republic is located in the biogeographically significant region of Central Asia and is home to more than 3,000 species of plants and about 500 species of vertebrates, including rare and endemic species such as the snow leopard and Greig's tulip.\n\n Kyrgyzstan is one of the world's priority ecoregions and is included in the list of global \"hotspots of biodiversity.\" About 2% of the world's flora and more than 3% of the world's fauna are concentrated in an area that makes up only 0.039% of the planet's surface. \n\n The country has three wetlands of international importance, 11 important ornithological areas, and two biosphere reserves. The Red Book of the Kyrgyz Republic includes 57 species of birds, 23 species of mammals, 2 species of amphibians, 8 species of reptiles, 7 species of fish, 18 species of arthropods, as well as 87 species of higher plants and fungi that are threatened with extinction. \n\n Over the past decades, there has been a decline in the number of a number of species and a deterioration in the state of ecosystems, which underscores the key role of the system of specially protected natural areas in preserving the country's biodiversity. As of early 2025, Kyrgyzstan has 10 nature reserves, 13 national parks, and dozens of wildlife sanctuaries covering over 1.5 million hectares.",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 4,
		image: '/imgs/regions/kg/kg-ff-4.webp',
		title: {
			kk: 'Қырғыз Республикасының флорасы мен фаунасы',
			ru: 'Флора и фауна Кыргызской Республики',
			en: 'Flora and fauna of the Kyrgyz Republic',
		},
		description: {
			kk: 'Қырғыз Республикасының табиғи әртүрлілігі таулы экожүйелердің басымдығы және табиғи аймақтардың кең спектрі арқылы қалыптасады - далалық және ормандықтан бастап субальпілік және альпілікке дейін. Республика Орталық Азияның биогеографиялық маңызды аймағында орналасқан және 3000-нан астам өсімдік түрлері мен шамамен 500 омыртқалы жануарлар түрлерінің мекені, соның ішінде қар барысы және Грейг лалагүлі сияқты сирек және эндемикалық түрлер. \n\n Қырғызстан әлемнің басымдық экоаймақтарының қатарына жатады және жаһандық «биоәртүрлілік ошақтарының» тізіміне кіреді. Планета аумағының тек 0,039% құрайтын аумақта әлемдік флораның шамамен 2% және әлемдік фаунаның 3%-дан астамы шоғырланған. \n\n Елде халықаралық маңызы бар үш сулы-батпақты жерлер, 11 маңызды орнитологиялық аумақтар және екі биосфералық қорық орналасқан. Қырғыз Республикасының Қызыл кітабына 57 құс түрі, 23 сүтқоректі түрі, 2 қосмекенді түрі, 8 бауырымен жорғалаушы түрі, 7 балық түрі, 18 буынаяқты түрі, сондай-ақ жойылу қаупі төнген 87 жоғары өсімдіктер мен саңырауқұлақтар түрі енгізілген. \n\n Соңғы онжылдықтарда бірқатар түрлердің санының азаюы және экожүйелердің жағдайының нашарлауы байқалды, бұл елдің биоәртүрлілігін сақтауда ерекше қорғалатын табиғи аумақтар жүйесінің негізгі рөлін атап көрсетеді. 2025 жылдың басына қарай Қырғызстанда 10 қорық, 13 ұлттық саябақ және 1,5 млн гектардан астам аумақты қамтитын ондаған заказниктер жұмыс істеп жатыр.',
			ru: 'Природное разнообразие Кыргызской Республики формируется за счёт преобладания горных экосистем и широкого спектра природных зон - от степных и лесных до субальпийских и альпийских. Республика расположена в биогеографически значимом регионе Центральной Азии и является местом обитания более 3 000 видов растений и около 500 видов позвоночных животных, включая редкие и эндемичные виды, такие как снежный барс и тюльпан Грейга. \n\n Кыргызстан относится к числу приоритетных экорегионов мира и входит в перечень глобальных «очагов биоразнообразия». На территории, составляющей лишь 0,039% площади планеты, сосредоточено около 2% мировой флоры и более 3% мировой фауны. \n\n В стране расположены три водно-болотных угодья международного значения, 11 важных орнитологических территорий и два биосферных заповедника. В Красную книгу Кыргызской Республики включены 57 видов птиц, 23 вида млекопитающих, 2 вида амфибий, 8 видов рептилий, 7 видов рыб, 18 видов членистоногих, а также 87 видов высших растений и грибов, находящихся под угрозой исчезновения. \n\n За последние десятилетия отмечается сокращение численности ряда видов и ухудшение состояния экосистем, что подчёркивает ключевую роль системы особо охраняемых природных территорий в сохранении биоразнообразия страны. На начало 2025 года в Кыргызстане функционируют 10 заповедников, 13 национальных парков и десятки заказников, охватывающие свыше 1,5 млн гектаров.',
			en: "The natural diversity of the Kyrgyz Republic is formed by the predominance of mountain ecosystems and a wide range of natural zones - from steppe and forest to subalpine and alpine. The republic is located in the biogeographically significant region of Central Asia and is home to more than 3,000 species of plants and about 500 species of vertebrates, including rare and endemic species such as the snow leopard and Greig's tulip.\n\n Kyrgyzstan is one of the world's priority ecoregions and is included in the list of global \"hotspots of biodiversity.\" About 2% of the world's flora and more than 3% of the world's fauna are concentrated in an area that makes up only 0.039% of the planet's surface. \n\n The country has three wetlands of international importance, 11 important ornithological areas, and two biosphere reserves. The Red Book of the Kyrgyz Republic includes 57 species of birds, 23 species of mammals, 2 species of amphibians, 8 species of reptiles, 7 species of fish, 18 species of arthropods, as well as 87 species of higher plants and fungi that are threatened with extinction. \n\n Over the past decades, there has been a decline in the number of a number of species and a deterioration in the state of ecosystems, which underscores the key role of the system of specially protected natural areas in preserving the country's biodiversity. As of early 2025, Kyrgyzstan has 10 nature reserves, 13 national parks, and dozens of wildlife sanctuaries covering over 1.5 million hectares.",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 5,
		image: '/imgs/regions/kg/kg-ff-5.webp',
		title: {
			kk: 'Қырғыз Республикасының флорасы мен фаунасы',
			ru: 'Флора и фауна Кыргызской Республики',
			en: 'Flora and fauna of the Kyrgyz Republic',
		},
		description: {
			kk: 'Қырғыз Республикасының табиғи әртүрлілігі таулы экожүйелердің басымдығы және табиғи аймақтардың кең спектрі арқылы қалыптасады - далалық және ормандықтан бастап субальпілік және альпілікке дейін. Республика Орталық Азияның биогеографиялық маңызды аймағында орналасқан және 3000-нан астам өсімдік түрлері мен шамамен 500 омыртқалы жануарлар түрлерінің мекені, соның ішінде қар барысы және Грейг лалагүлі сияқты сирек және эндемикалық түрлер. \n\n Қырғызстан әлемнің басымдық экоаймақтарының қатарына жатады және жаһандық «биоәртүрлілік ошақтарының» тізіміне кіреді. Планета аумағының тек 0,039% құрайтын аумақта әлемдік флораның шамамен 2% және әлемдік фаунаның 3%-дан астамы шоғырланған. \n\n Елде халықаралық маңызы бар үш сулы-батпақты жерлер, 11 маңызды орнитологиялық аумақтар және екі биосфералық қорық орналасқан. Қырғыз Республикасының Қызыл кітабына 57 құс түрі, 23 сүтқоректі түрі, 2 қосмекенді түрі, 8 бауырымен жорғалаушы түрі, 7 балық түрі, 18 буынаяқты түрі, сондай-ақ жойылу қаупі төнген 87 жоғары өсімдіктер мен саңырауқұлақтар түрі енгізілген. \n\n Соңғы онжылдықтарда бірқатар түрлердің санының азаюы және экожүйелердің жағдайының нашарлауы байқалды, бұл елдің биоәртүрлілігін сақтауда ерекше қорғалатын табиғи аумақтар жүйесінің негізгі рөлін атап көрсетеді. 2025 жылдың басына қарай Қырғызстанда 10 қорық, 13 ұлттық саябақ және 1,5 млн гектардан астам аумақты қамтитын ондаған заказниктер жұмыс істеп жатыр.',
			ru: 'Природное разнообразие Кыргызской Республики формируется за счёт преобладания горных экосистем и широкого спектра природных зон - от степных и лесных до субальпийских и альпийских. Республика расположена в биогеографически значимом регионе Центральной Азии и является местом обитания более 3 000 видов растений и около 500 видов позвоночных животных, включая редкие и эндемичные виды, такие как снежный барс и тюльпан Грейга. \n\n Кыргызстан относится к числу приоритетных экорегионов мира и входит в перечень глобальных «очагов биоразнообразия». На территории, составляющей лишь 0,039% площади планеты, сосредоточено около 2% мировой флоры и более 3% мировой фауны. \n\n В стране расположены три водно-болотных угодья международного значения, 11 важных орнитологических территорий и два биосферных заповедника. В Красную книгу Кыргызской Республики включены 57 видов птиц, 23 вида млекопитающих, 2 вида амфибий, 8 видов рептилий, 7 видов рыб, 18 видов членистоногих, а также 87 видов высших растений и грибов, находящихся под угрозой исчезновения. \n\n За последние десятилетия отмечается сокращение численности ряда видов и ухудшение состояния экосистем, что подчёркивает ключевую роль системы особо охраняемых природных территорий в сохранении биоразнообразия страны. На начало 2025 года в Кыргызстане функционируют 10 заповедников, 13 национальных парков и десятки заказников, охватывающие свыше 1,5 млн гектаров.',
			en: "The natural diversity of the Kyrgyz Republic is formed by the predominance of mountain ecosystems and a wide range of natural zones - from steppe and forest to subalpine and alpine. The republic is located in the biogeographically significant region of Central Asia and is home to more than 3,000 species of plants and about 500 species of vertebrates, including rare and endemic species such as the snow leopard and Greig's tulip.\n\n Kyrgyzstan is one of the world's priority ecoregions and is included in the list of global \"hotspots of biodiversity.\" About 2% of the world's flora and more than 3% of the world's fauna are concentrated in an area that makes up only 0.039% of the planet's surface. \n\n The country has three wetlands of international importance, 11 important ornithological areas, and two biosphere reserves. The Red Book of the Kyrgyz Republic includes 57 species of birds, 23 species of mammals, 2 species of amphibians, 8 species of reptiles, 7 species of fish, 18 species of arthropods, as well as 87 species of higher plants and fungi that are threatened with extinction. \n\n Over the past decades, there has been a decline in the number of a number of species and a deterioration in the state of ecosystems, which underscores the key role of the system of specially protected natural areas in preserving the country's biodiversity. As of early 2025, Kyrgyzstan has 10 nature reserves, 13 national parks, and dozens of wildlife sanctuaries covering over 1.5 million hectares.",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 6,
		image: '/imgs/regions/kg/kg-ff-6.webp',
		title: {
			kk: 'Қырғыз Республикасының флорасы мен фаунасы',
			ru: 'Флора и фауна Кыргызской Республики',
			en: 'Flora and fauna of the Kyrgyz Republic',
		},
		description: {
			kk: 'Қырғыз Республикасының табиғи әртүрлілігі таулы экожүйелердің басымдығы және табиғи аймақтардың кең спектрі арқылы қалыптасады - далалық және ормандықтан бастап субальпілік және альпілікке дейін. Республика Орталық Азияның биогеографиялық маңызды аймағында орналасқан және 3000-нан астам өсімдік түрлері мен шамамен 500 омыртқалы жануарлар түрлерінің мекені, соның ішінде қар барысы және Грейг лалагүлі сияқты сирек және эндемикалық түрлер. \n\n Қырғызстан әлемнің басымдық экоаймақтарының қатарына жатады және жаһандық «биоәртүрлілік ошақтарының» тізіміне кіреді. Планета аумағының тек 0,039% құрайтын аумақта әлемдік флораның шамамен 2% және әлемдік фаунаның 3%-дан астамы шоғырланған. \n\n Елде халықаралық маңызы бар үш сулы-батпақты жерлер, 11 маңызды орнитологиялық аумақтар және екі биосфералық қорық орналасқан. Қырғыз Республикасының Қызыл кітабына 57 құс түрі, 23 сүтқоректі түрі, 2 қосмекенді түрі, 8 бауырымен жорғалаушы түрі, 7 балық түрі, 18 буынаяқты түрі, сондай-ақ жойылу қаупі төнген 87 жоғары өсімдіктер мен саңырауқұлақтар түрі енгізілген. \n\n Соңғы онжылдықтарда бірқатар түрлердің санының азаюы және экожүйелердің жағдайының нашарлауы байқалды, бұл елдің биоәртүрлілігін сақтауда ерекше қорғалатын табиғи аумақтар жүйесінің негізгі рөлін атап көрсетеді. 2025 жылдың басына қарай Қырғызстанда 10 қорық, 13 ұлттық саябақ және 1,5 млн гектардан астам аумақты қамтитын ондаған заказниктер жұмыс істеп жатыр.',
			ru: 'Природное разнообразие Кыргызской Республики формируется за счёт преобладания горных экосистем и широкого спектра природных зон - от степных и лесных до субальпийских и альпийских. Республика расположена в биогеографически значимом регионе Центральной Азии и является местом обитания более 3 000 видов растений и около 500 видов позвоночных животных, включая редкие и эндемичные виды, такие как снежный барс и тюльпан Грейга. \n\n Кыргызстан относится к числу приоритетных экорегионов мира и входит в перечень глобальных «очагов биоразнообразия». На территории, составляющей лишь 0,039% площади планеты, сосредоточено около 2% мировой флоры и более 3% мировой фауны. \n\n В стране расположены три водно-болотных угодья международного значения, 11 важных орнитологических территорий и два биосферных заповедника. В Красную книгу Кыргызской Республики включены 57 видов птиц, 23 вида млекопитающих, 2 вида амфибий, 8 видов рептилий, 7 видов рыб, 18 видов членистоногих, а также 87 видов высших растений и грибов, находящихся под угрозой исчезновения. \n\n За последние десятилетия отмечается сокращение численности ряда видов и ухудшение состояния экосистем, что подчёркивает ключевую роль системы особо охраняемых природных территорий в сохранении биоразнообразия страны. На начало 2025 года в Кыргызстане функционируют 10 заповедников, 13 национальных парков и десятки заказников, охватывающие свыше 1,5 млн гектаров.',
			en: "The natural diversity of the Kyrgyz Republic is formed by the predominance of mountain ecosystems and a wide range of natural zones - from steppe and forest to subalpine and alpine. The republic is located in the biogeographically significant region of Central Asia and is home to more than 3,000 species of plants and about 500 species of vertebrates, including rare and endemic species such as the snow leopard and Greig's tulip.\n\n Kyrgyzstan is one of the world's priority ecoregions and is included in the list of global \"hotspots of biodiversity.\" About 2% of the world's flora and more than 3% of the world's fauna are concentrated in an area that makes up only 0.039% of the planet's surface. \n\n The country has three wetlands of international importance, 11 important ornithological areas, and two biosphere reserves. The Red Book of the Kyrgyz Republic includes 57 species of birds, 23 species of mammals, 2 species of amphibians, 8 species of reptiles, 7 species of fish, 18 species of arthropods, as well as 87 species of higher plants and fungi that are threatened with extinction. \n\n Over the past decades, there has been a decline in the number of a number of species and a deterioration in the state of ecosystems, which underscores the key role of the system of specially protected natural areas in preserving the country's biodiversity. As of early 2025, Kyrgyzstan has 10 nature reserves, 13 national parks, and dozens of wildlife sanctuaries covering over 1.5 million hectares.",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
	{
		id: 7,
		image: '/imgs/regions/kg/kg-ff-7.webp',
		title: {
			kk: 'Қырғыз Республикасының флорасы мен фаунасы',
			ru: 'Флора и фауна Кыргызской Республики',
			en: 'Flora and fauna of the Kyrgyz Republic',
		},
		description: {
			kk: 'Қырғыз Республикасының табиғи әртүрлілігі таулы экожүйелердің басымдығы және табиғи аймақтардың кең спектрі арқылы қалыптасады - далалық және ормандықтан бастап субальпілік және альпілікке дейін. Республика Орталық Азияның биогеографиялық маңызды аймағында орналасқан және 3000-нан астам өсімдік түрлері мен шамамен 500 омыртқалы жануарлар түрлерінің мекені, соның ішінде қар барысы және Грейг лалагүлі сияқты сирек және эндемикалық түрлер. \n\n Қырғызстан әлемнің басымдық экоаймақтарының қатарына жатады және жаһандық «биоәртүрлілік ошақтарының» тізіміне кіреді. Планета аумағының тек 0,039% құрайтын аумақта әлемдік флораның шамамен 2% және әлемдік фаунаның 3%-дан астамы шоғырланған. \n\n Елде халықаралық маңызы бар үш сулы-батпақты жерлер, 11 маңызды орнитологиялық аумақтар және екі биосфералық қорық орналасқан. Қырғыз Республикасының Қызыл кітабына 57 құс түрі, 23 сүтқоректі түрі, 2 қосмекенді түрі, 8 бауырымен жорғалаушы түрі, 7 балық түрі, 18 буынаяқты түрі, сондай-ақ жойылу қаупі төнген 87 жоғары өсімдіктер мен саңырауқұлақтар түрі енгізілген. \n\n Соңғы онжылдықтарда бірқатар түрлердің санының азаюы және экожүйелердің жағдайының нашарлауы байқалды, бұл елдің биоәртүрлілігін сақтауда ерекше қорғалатын табиғи аумақтар жүйесінің негізгі рөлін атап көрсетеді. 2025 жылдың басына қарай Қырғызстанда 10 қорық, 13 ұлттық саябақ және 1,5 млн гектардан астам аумақты қамтитын ондаған заказниктер жұмыс істеп жатыр.',
			ru: 'Природное разнообразие Кыргызской Республики формируется за счёт преобладания горных экосистем и широкого спектра природных зон - от степных и лесных до субальпийских и альпийских. Республика расположена в биогеографически значимом регионе Центральной Азии и является местом обитания более 3 000 видов растений и около 500 видов позвоночных животных, включая редкие и эндемичные виды, такие как снежный барс и тюльпан Грейга. \n\n Кыргызстан относится к числу приоритетных экорегионов мира и входит в перечень глобальных «очагов биоразнообразия». На территории, составляющей лишь 0,039% площади планеты, сосредоточено около 2% мировой флоры и более 3% мировой фауны. \n\n В стране расположены три водно-болотных угодья международного значения, 11 важных орнитологических территорий и два биосферных заповедника. В Красную книгу Кыргызской Республики включены 57 видов птиц, 23 вида млекопитающих, 2 вида амфибий, 8 видов рептилий, 7 видов рыб, 18 видов членистоногих, а также 87 видов высших растений и грибов, находящихся под угрозой исчезновения. \n\n За последние десятилетия отмечается сокращение численности ряда видов и ухудшение состояния экосистем, что подчёркивает ключевую роль системы особо охраняемых природных территорий в сохранении биоразнообразия страны. На начало 2025 года в Кыргызстане функционируют 10 заповедников, 13 национальных парков и десятки заказников, охватывающие свыше 1,5 млн гектаров.',
			en: "The natural diversity of the Kyrgyz Republic is formed by the predominance of mountain ecosystems and a wide range of natural zones - from steppe and forest to subalpine and alpine. The republic is located in the biogeographically significant region of Central Asia and is home to more than 3,000 species of plants and about 500 species of vertebrates, including rare and endemic species such as the snow leopard and Greig's tulip.\n\n Kyrgyzstan is one of the world's priority ecoregions and is included in the list of global \"hotspots of biodiversity.\" About 2% of the world's flora and more than 3% of the world's fauna are concentrated in an area that makes up only 0.039% of the planet's surface. \n\n The country has three wetlands of international importance, 11 important ornithological areas, and two biosphere reserves. The Red Book of the Kyrgyz Republic includes 57 species of birds, 23 species of mammals, 2 species of amphibians, 8 species of reptiles, 7 species of fish, 18 species of arthropods, as well as 87 species of higher plants and fungi that are threatened with extinction. \n\n Over the past decades, there has been a decline in the number of a number of species and a deterioration in the state of ecosystems, which underscores the key role of the system of specially protected natural areas in preserving the country's biodiversity. As of early 2025, Kyrgyzstan has 10 nature reserves, 13 national parks, and dozens of wildlife sanctuaries covering over 1.5 million hectares.",
		},
		alt: 'flora-and-fauna',
		width: 1793,
		height: 888,
	},
]
