import { NewsItemProps } from '@/entities/news/NewsItem'

export const newsPaginItems: NewsItemProps[] = [
	{
		title: {
			ru: 'Механизм достижения климатических амбиций',
			kk: 'Климаттық амбицияларға қол жеткізу механизмі',
			en: 'Mechanism for achieving climate ambitions',
		},
		image: '/imgs/news-wide-item.png',
		date: {
			ru: '26 декабря 2026',
			kk: '2026 жылдың 26 желтоқсаны',
			en: 'December 26, 2026',
		},
		tag: {
			ru: 'Экология и окружающая среда',
			kk: 'Экология және қоршаған орта',
			en: 'Ecology and environment',
		},
		slug: 'summit-climate-ambitions',
		wide: true,
		variant: 'dark',
		type: 'release',
		content: {
			ru: '',
			kk: '',
			en: '',
		},
		views: 3420,
	},
	{
		title: {
			ru: 'Что нужно знать о Саммите по климатической амбициозности?',
			kk: 'Климаттық амбициоздылық саммиті туралы не білу керек?',
			en: 'What you need to know about the Climate Ambition Summit?',
		},
		image: '/imgs/news-1.png',
		date: {
			ru: '26 декабря 2026',
			kk: '2026 жылдың 26 желтоқсаны',
			en: 'December 26, 2026',
		},
		tag: {
			ru: 'Экология и окружающая среда',
			kk: 'Экология және қоршаған орта',
			en: 'Ecology and environment',
		},
		slug: 'summit-climate-ambitions',
		variant: 'light',
		type: 'anounce',
		content: {
			ru: '',
			kk: '',
			en: '',
		},
		views: 1250,
	},
	{
		title: {
			ru: 'Механизм достижения климатических амбиций',
			kk: 'Климаттық амбицияларға қол жеткізу механизмі',
			en: 'Mechanism for achieving climate ambitions',
		},
		image: '/imgs/news-2.png',
		date: {
			ru: '26 декабря 2026',
			kk: '2026 жылдың 26 желтоқсаны',
			en: 'December 26, 2026',
		},
		tag: {
			ru: 'Экология и окружающая среда',
			kk: 'Экология және қоршаған орта',
			en: 'Ecology and environment',
		},
		slug: 'climate-mechanism',
		variant: 'dark',
		type: 'release',
		content: {
			ru: '',
			kk: '',
			en: '',
		},
		views: 892,
	},
	{
		title: {
			ru: 'Что нужно знать о Саммите по климатической амбициозности?',
			kk: 'Климаттық амбициоздылық саммиті туралы не білу керек?',
			en: 'What you need to know about the Climate Ambition Summit?',
		},
		image: '/imgs/news-3.png',
		date: {
			ru: '26 декабря 2026',
			kk: '2026 жылдың 26 желтоқсаны',
			en: 'December 26, 2026',
		},
		tag: {
			ru: 'Экология и окружающая среда',
			kk: 'Экология және қоршаған орта',
			en: 'Ecology and environment',
		},
		slug: 'summit-climate-ambitions-2',
		variant: 'light',
		type: 'anounce',
		content: {
			ru: '',
			kk: '',
			en: '',
		},
		views: 2145,
	},
	{
		title: {
			ru: 'Механизм достижения климатических амбиций',
			kk: 'Климаттық амбицияларға қол жеткізу механизмі',
			en: 'Mechanism for achieving climate ambitions',
		},
		image: '/imgs/news-4.png',
		date: {
			ru: '26 декабря 2026',
			kk: '2026 жылдың 26 желтоқсаны',
			en: 'December 26, 2026',
		},
		tag: {
			ru: 'Экология и окружающая среда',
			kk: 'Экология және қоршаған орта',
			en: 'Ecology and environment',
		},
		slug: 'climate-mechanism-2',
		variant: 'dark',
		type: 'release',
		content: {
			ru: '',
			kk: '',
			en: '',
		},
		views: 567,
	},
	{
		title: {
			ru: 'Механизм достижения климатических амбиций',
			kk: 'Климаттық амбицияларға қол жеткізу механизмі',
			en: 'Mechanism for achieving climate ambitions',
		},
		image: '/imgs/news-2.png',
		date: {
			ru: '26 декабря 2026',
			kk: '2026 жылдың 26 желтоқсаны',
			en: 'December 26, 2026',
		},
		tag: {
			ru: 'Экология и окружающая среда',
			kk: 'Экология және қоршаған орта',
			en: 'Ecology and environment',
		},
		slug: 'climate-mechanism',
		variant: 'dark',
		type: 'anounce',
		content: {
			ru: '',
			kk: '',
			en: '',
		},
		views: 1834,
	},
	{
		title: {
			ru: 'Что нужно знать о Саммите по климатической амбициозности?',
			kk: 'Климаттық амбициоздылық саммиті туралы не білу керек?',
			en: 'What you need to know about the Climate Ambition Summit?',
		},
		image: '/imgs/news-3.png',
		date: {
			ru: '26 декабря 2026',
			kk: '2026 жылдың 26 желтоқсаны',
			en: 'December 26, 2026',
		},
		tag: {
			ru: 'Экология и окружающая среда',
			kk: 'Экология және қоршаған орта',
			en: 'Ecology and environment',
		},
		slug: 'summit-climate-ambitions-2',
		variant: 'light',
		type: 'release',
		content: {
			ru: '',
			kk: '',
			en: '',
		},
		views: 756,
	},
	{
		title: {
			ru: 'Механизм достижения климатических амбиций',
			kk: 'Климаттық амбицияларға қол жеткізу механизмі',
			en: 'Mechanism for achieving climate ambitions',
		},
		image: '/imgs/news-4.png',
		date: {
			ru: '26 декабря 2026',
			kk: '2026 жылдың 26 желтоқсаны',
			en: 'December 26, 2026',
		},
		tag: {
			ru: 'Экология и окружающая среда',
			kk: 'Экология және қоршаған орта',
			en: 'Ecology and environment',
		},
		slug: 'climate-mechanism-2',
		variant: 'dark',
		type: 'anounce',
		content: {
			ru: '',
			kk: '',
			en: '',
		},
		views: 2901,
	},
	{
		title: {
			ru: 'Механизм достижения климатических амбиций',
			kk: 'Климаттық амбицияларға қол жеткізу механизмі',
			en: 'Mechanism for achieving climate ambitions',
		},
		image: '/imgs/news-2.png',
		date: {
			ru: '26 декабря 2026',
			kk: '2026 жылдың 26 желтоқсаны',
			en: 'December 26, 2026',
		},
		tag: {
			ru: 'Экология и окружающая среда',
			kk: 'Экология және қоршаған орта',
			en: 'Ecology and environment',
		},
		slug: 'climate-mechanism',
		variant: 'dark',
		type: 'release',
		content: {
			ru: '',
			kk: '',
			en: '',
		},
		views: 1123,
	},
	{
		title: {
			ru: 'Что нужно знать о Саммите по климатической амбициозности?',
			kk: 'Климаттық амбициоздылық саммиті туралы не білу керек?',
			en: 'What you need to know about the Climate Ambition Summit?',
		},
		image: '/imgs/news-3.png',
		date: {
			ru: '26 декабря 2026',
			kk: '2026 жылдың 26 желтоқсаны',
			en: 'December 26, 2026',
		},
		tag: {
			ru: 'Экология и окружающая среда',
			kk: 'Экология және қоршаған орта',
			en: 'Ecology and environment',
		},
		slug: 'summit-climate-ambitions-2',
		variant: 'light',
		type: 'anounce',
		content: {
			ru: '',
			kk: '',
			en: '',
		},
		views: 1987,
	},
	{
		title: {
			ru: 'Механизм достижения климатических амбиций',
			kk: 'Климаттық амбицияларға қол жеткізу механизмі',
			en: 'Mechanism for achieving climate ambitions',
		},
		image: '/imgs/news-4.png',
		date: {
			ru: '26 декабря 2026',
			kk: '2026 жылдың 26 желтоқсаны',
			en: 'December 26, 2026',
		},
		tag: {
			ru: 'Экология и окружающая среда',
			kk: 'Экология және қоршаған орта',
			en: 'Ecology and environment',
		},
		slug: 'climate-mechanism-2',
		variant: 'dark',
		type: 'release',
		content: {
			ru: '',
			kk: '',
			en: '',
		},
		views: 445,
	},
]
