import { NewsItemProps } from '@/entities/news/NewsItem'

export const newsPaginItems: NewsItemProps[] = [
	{
		title: 'Механизм достижения климатических амбиций',
		image: '/imgs/news-wide-item.png',
		date: '26 декабря 2026',
		tag: 'Экология и окружающая среда',
		slug: 'summit-climate-ambitions',
		wide: true,
		variant: 'dark',
		type: 'release',
		content: ``,
		views: 3420,
	},
	{
		title: 'Что нужно знать о Саммите по климатической амбициозности?',
		image: '/imgs/news-1.png',
		date: '26 декабря 2026',
		tag: 'Экология и окружающая среда',
		slug: 'summit-climate-ambitions',
		variant: 'light',
		type: 'anounce',
		content: ``,
		views: 1250,
	},
	{
		title: 'Механизм достижения климатических амбиций',
		image: '/imgs/news-2.png',
		date: '26 декабря 2026',
		tag: 'Экология и окружающая среда',
		slug: 'climate-mechanism',
		variant: 'dark',
		type: 'release',
		content: ``,
		views: 892,
	},
	{
		title: 'Что нужно знать о Саммите по климатической амбициозности?',
		image: '/imgs/news-3.png',
		date: '26 декабря 2026',
		tag: 'Экология и окружающая среда',
		slug: 'summit-climate-ambitions-2',
		variant: 'light',
		type: 'anounce',
		content: ``,
		views: 2145,
	},
	{
		title: 'Механизм достижения климатических амбиций',
		image: '/imgs/news-4.png',
		date: '26 декабря 2026',
		tag: 'Экология и окружающая среда',
		slug: 'climate-mechanism-2',
		variant: 'dark',
		type: 'release',
		content: ``,
		views: 567,
	},
	{
		title: 'Механизм достижения климатических амбиций',
		image: '/imgs/news-2.png',
		date: '26 декабря 2026',
		tag: 'Экология и окружающая среда',
		slug: 'climate-mechanism',
		variant: 'dark',
		type: 'anounce',
		content: ``,
		views: 1834,
	},
	{
		title: 'Что нужно знать о Саммите по климатической амбициозности?',
		image: '/imgs/news-3.png',
		date: '26 декабря 2026',
		tag: 'Экология и окружающая среда',
		slug: 'summit-climate-ambitions-2',
		variant: 'light',
		type: 'release',
		content: ``,
		views: 756,
	},
	{
		title: 'Механизм достижения климатических амбиций',
		image: '/imgs/news-4.png',
		date: '26 декабря 2026',
		tag: 'Экология и окружающая среда',
		slug: 'climate-mechanism-2',
		variant: 'dark',
		type: 'anounce',
		content: ``,
		views: 2901,
	},
	{
		title: 'Механизм достижения климатических амбиций',
		image: '/imgs/news-2.png',
		date: '26 декабря 2026',
		tag: 'Экология и окружающая среда',
		slug: 'climate-mechanism',
		variant: 'dark',
		type: 'release',
		content: ``,
		views: 1123,
	},
	{
		title: 'Что нужно знать о Саммите по климатической амбициозности?',
		image: '/imgs/news-3.png',
		date: '26 декабря 2026',
		tag: 'Экология и окружающая среда',
		slug: 'summit-climate-ambitions-2',
		variant: 'light',
		type: 'anounce',
		content: ``,
		views: 1987,
	},
	{
		title: 'Механизм достижения климатических амбиций',
		image: '/imgs/news-4.png',
		date: '26 декабря 2026',
		tag: 'Экология и окружающая среда',
		slug: 'climate-mechanism-2',
		variant: 'dark',
		type: 'release',
		content: ``,
		views: 445,
	},
]
