export const hotels = [
	{
		id: 1,
		title: 'The Ritz-Carlton',
		slug: 'the-ritz-carlton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/ritz-carlton.png',
		description: 'Отель The Ritz-Carlton, Astana — это современный и уникальный отель класса люкс в новом центре столицы.',
		buttonText: 'Забронировать',
		link: '/hotels/the-ritz-carlton-astana',
	},
	{
		id: 2,
		title: 'The St. Regis Astana',
		slug: 'the-st-regis-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/st-regis.png',
		description: 'The St. Regis Astana предлагает роскошные номера с видом на реку и высокий уровень сервиса.',
		buttonText: 'Забронировать',
		link: '/hotels/the-st-regis-astana',
	},
	{
		id: 3,
		title: 'Hilton Astana',
		slug: 'hilton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/hilton.png',
		description: 'Hilton Astana — современный отель с развитой инфраструктурой, идеально подходящий для бизнеса и отдыха.',
		buttonText: 'Забронировать',
		link: '/hotels/hilton-astana',
	},
	{
		id: 4,
		title: 'Отель The Ritz-Carlton, Astana',
		slug: 'otel-the-ritz-carlton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/ritz-carlton-2.png',
		description: 'Современный люксовый отель с панорамными видами и первоклассным обслуживанием.',
		buttonText: 'Забронировать',
		link: '/hotels/otel-the-ritz-carlton-astana',
	},
	{
		id: 5,
		title: 'The Ritz-Carlton',
		slug: 'the-ritz-carlton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/ritz-carlton.png',
		description: 'Отель The Ritz-Carlton, Astana — это современный и уникальный отель класса люкс в новом центре столицы.',
		buttonText: 'Забронировать',
		link: '/hotels/the-ritz-carlton-astana',
	},
	{
		id: 6,
		title: 'The St. Regis Astana',
		slug: 'the-st-regis-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/st-regis.png',
		description: 'The St. Regis Astana предлагает роскошные номера с видом на реку и высокий уровень сервиса.',
		buttonText: 'Забронировать',
		link: '/hotels/the-st-regis-astana',
	},
	{
		id: 7,
		title: 'Hilton Astana',
		slug: 'hilton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/hilton.png',
		description: 'Hilton Astana — современный отель с развитой инфраструктурой, идеально подходящий для бизнеса и отдыха.',
		buttonText: 'Забронировать',
		link: '/hotels/hilton-astana',
	},
	{
		id: 8,
		title: 'Отель The Ritz-Carlton, Astana',
		slug: 'otel-the-ritz-carlton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/ritz-carlton-2.png',
		description: 'Современный люксовый отель с панорамными видами и первоклассным обслуживанием.',
		buttonText: 'Забронировать',
		link: '/hotels/otel-the-ritz-carlton-astana',
	},
]
