import { HotelItemMultilang, Locale } from './hotel.types'

export const hotelsMultilang: HotelItemMultilang[] = [
	{
		id: 1,
		title: {
			ru: 'The Ritz-Carlton',
			kk: 'The Ritz-Carlton',
			en: 'The Ritz-Carlton',
		},
		slug: 'the-ritz-carlton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/ritz-carlton.png',
		description: {
			ru: 'Отель The Ritz-Carlton, Astana — это современный и уникальный отель класса люкс в новом центре столицы.',
			kk: 'The Ritz-Carlton, Astana қонақ үйі — астананың жаңа орталығындағы заманауи және бірегей люкс класс қонақ үйі.',
			en: 'The Ritz-Carlton, Astana is a modern and unique luxury hotel in the new center of the capital.',
		},
		buttonText: {
			ru: 'Забронировать',
			kk: 'Брондау',
			en: 'Book',
		},
		link: '/hotels/the-ritz-carlton-astana',
	},
	{
		id: 2,
		title: {
			ru: 'The St. Regis Astana',
			kk: 'The St. Regis Astana',
			en: 'The St. Regis Astana',
		},
		slug: 'the-st-regis-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/st-regis.png',
		description: {
			ru: 'The St. Regis Astana предлагает роскошные номера с видом на реку и высокий уровень сервиса.',
			kk: 'The St. Regis Astana өзенге қарайтын көрікті нөмерлер мен жоғары деңгейдегі қызмет көрсетеді.',
			en: 'The St. Regis Astana offers luxurious rooms with river views and high-level service.',
		},
		buttonText: {
			ru: 'Забронировать',
			kk: 'Брондау',
			en: 'Book',
		},
		link: '/hotels/the-st-regis-astana',
	},
	{
		id: 3,
		title: {
			ru: 'Hilton Astana',
			kk: 'Hilton Astana',
			en: 'Hilton Astana',
		},
		slug: 'hilton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/hilton.png',
		description: {
			ru: 'Hilton Astana — современный отель с развитой инфраструктурой, идеально подходящий для бизнеса и отдыха.',
			kk: 'Hilton Astana — дамыған инфрақұрылымы бар заманауи қонақ үй, бизнес және демалыс үшін идеалды.',
			en: 'Hilton Astana is a modern hotel with developed infrastructure, ideal for business and leisure.',
		},
		buttonText: {
			ru: 'Забронировать',
			kk: 'Брондау',
			en: 'Book',
		},
		link: '/hotels/hilton-astana',
	},
	{
		id: 4,
		title: {
			ru: 'Отель The Ritz-Carlton, Astana',
			kk: 'The Ritz-Carlton, Astana қонақ үйі',
			en: 'The Ritz-Carlton Hotel, Astana',
		},
		slug: 'otel-the-ritz-carlton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/ritz-carlton-2.png',
		description: {
			ru: 'Современный люксовый отель с панорамными видами и первоклассным обслуживанием.',
			kk: 'Панорамалық көріністері мен бірінші класс қызметі бар заманауи люкс қонақ үй.',
			en: 'A modern luxury hotel with panoramic views and first-class service.',
		},
		buttonText: {
			ru: 'Забронировать',
			kk: 'Брондау',
			en: 'Book',
		},
		link: '/hotels/otel-the-ritz-carlton-astana',
	},
	{
		id: 5,
		title: {
			ru: 'The Ritz-Carlton',
			kk: 'The Ritz-Carlton',
			en: 'The Ritz-Carlton',
		},
		slug: 'the-ritz-carlton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/ritz-carlton.png',
		description: {
			ru: 'Отель The Ritz-Carlton, Astana — это современный и уникальный отель класса люкс в новом центре столицы.',
			kk: 'The Ritz-Carlton, Astana қонақ үйі — астананың жаңа орталығындағы заманауи және бірегей люкс класс қонақ үйі.',
			en: 'The Ritz-Carlton, Astana is a modern and unique luxury hotel in the new center of the capital.',
		},
		buttonText: {
			ru: 'Забронировать',
			kk: 'Брондау',
			en: 'Book',
		},
		link: '/hotels/the-ritz-carlton-astana',
	},
	{
		id: 6,
		title: {
			ru: 'The St. Regis Astana',
			kk: 'The St. Regis Astana',
			en: 'The St. Regis Astana',
		},
		slug: 'the-st-regis-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/st-regis.png',
		description: {
			ru: 'The St. Regis Astana предлагает роскошные номера с видом на реку и высокий уровень сервиса.',
			kk: 'The St. Regis Astana өзенге қарайтын көрікті нөмерлер мен жоғары деңгейдегі қызмет көрсетеді.',
			en: 'The St. Regis Astana offers luxurious rooms with river views and high-level service.',
		},
		buttonText: {
			ru: 'Забронировать',
			kk: 'Брондау',
			en: 'Book',
		},
		link: '/hotels/the-st-regis-astana',
	},
	{
		id: 7,
		title: {
			ru: 'Hilton Astana',
			kk: 'Hilton Astana',
			en: 'Hilton Astana',
		},
		slug: 'hilton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/hilton.png',
		description: {
			ru: 'Hilton Astana — современный отель с развитой инфраструктурой, идеально подходящий для бизнеса и отдыха.',
			kk: 'Hilton Astana — дамыған инфрақұрылымы бар заманауи қонақ үй, бизнес және демалыс үшін идеалды.',
			en: 'Hilton Astana is a modern hotel with developed infrastructure, ideal for business and leisure.',
		},
		buttonText: {
			ru: 'Забронировать',
			kk: 'Брондау',
			en: 'Book',
		},
		link: '/hotels/hilton-astana',
	},
	{
		id: 8,
		title: {
			ru: 'Отель The Ritz-Carlton, Astana',
			kk: 'The Ritz-Carlton, Astana қонақ үйі',
			en: 'The Ritz-Carlton Hotel, Astana',
		},
		slug: 'otel-the-ritz-carlton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/usefulls/ritz-carlton-2.png',
		description: {
			ru: 'Современный люксовый отель с панорамными видами и первоклассным обслуживанием.',
			kk: 'Панорамалық көріністері мен бірінші класс қызметі бар заманауи люкс қонақ үй.',
			en: 'A modern luxury hotel with panoramic views and first-class service.',
		},
		buttonText: {
			ru: 'Забронировать',
			kk: 'Брондау',
			en: 'Book',
		},
		link: '/hotels/otel-the-ritz-carlton-astana',
	},
]

export function getHotels(locale: Locale = 'ru') {
	return hotelsMultilang.map((hotel) => ({
		id: hotel.id,
		slug: hotel.slug,
		rating: hotel.rating,
		priceFrom: hotel.priceFrom,
		currency: hotel.currency,
		image: hotel.image,
		description: hotel.description[locale],
		link: hotel.link,
		title: hotel.title[locale],
		city: hotel.city,
		buttonText: hotel.buttonText[locale],
	}))
}
