import { HotelItemMultilang, Locale } from './hotel.types'

export const hotelsMultilang: HotelItemMultilang[] = [
	{
		id: 1,
		title: { ru: 'SAAD Hotel Astana', kk: 'SAAD Hotel Astana', en: 'SAAD Hotel Astana' },
		slug: 'saad-hotel-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 70000,
		currency: 'KZT',
		image: '/imgs/hotels/SAAD Hotel Astana.webp',
		description: {
			ru: 'Пятизвёздочный бизнес-отель в центре Астаны с высоким уровнем сервиса и современной инфраструктурой.',
			kk: 'Астананың орталығындағы жоғары сервисті және заманауи инфрақұрылымы бар бес жұлдызды бизнес-отель.',
			en: 'A five-star business hotel in the center of Astana with high service standards and modern infrastructure.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/astana-marriott-astana.ru.html',
	},
	{
		id: 2,
		title: { ru: 'Rixos President Astana', kk: 'Rixos President Astana', en: 'Rixos President Astana' },
		slug: 'rixos-president-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 70000,
		currency: 'KZT',
		image: '/imgs/hotels/Rixos President Astana.webp',
		description: {
			ru: 'Роскошный пятизвёздочный отель премиум-класса, ориентированный на деловых гостей и официальные визиты.',
			kk: 'Іскер қонақтар мен ресми сапарларға бағытталған премиум санаттағы сәнді бес жұлдызды қонақүй.',
			en: 'A luxury five-star premium hotel tailored for business guests and official visits.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/rixos-president-astana.ru.html',
	},
	{
		id: 3,
		title: { ru: 'Radisson Astana', kk: 'Radisson Astana', en: 'Radisson Astana' },
		slug: 'radisson-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 70000,
		currency: 'KZT',
		image: '/imgs/hotels/Radisson Astana.webp',
		description: {
			ru: 'Современный пятизвёздочный отель международной сети в престижном районе столицы.',
			kk: 'Елордадағы беделді ауданда орналасқан халықаралық желінің заманауи бес жұлдызды қонақүйі.',
			en: 'A modern five-star hotel from an international chain in a prestigious area of the capital.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/radisson-astana.ru.html',
	},
	{
		id: 4,
		title: { ru: 'Hilton Garden Inn Astana', kk: 'Hilton Garden Inn Astana', en: 'Hilton Garden Inn Astana' },
		slug: 'hilton-garden-inn-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 47000,
		currency: 'KZT',
		image: '/imgs/hotels/Hilton Garden Inn Astana.webp',
		description: {
			ru: 'Четырёхзвёздочный городской отель с удобным расположением и оптимальным соотношением цены и качества.',
			kk: 'Ыңғайлы орналасуы және баға мен сапаның оңтайлы үйлесімі бар төрт жұлдызды қалалық қонақүй.',
			en: 'A four-star city hotel with a convenient location and an optimal price-to-quality ratio.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/hilton-garden-inn-astana.ru.html',
	},
	{
		id: 5,
		title: { ru: 'Hilton Astana', kk: 'Hilton Astana', en: 'Hilton Astana' },
		slug: 'hilton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 69000,
		currency: 'KZT',
		image: '/imgs/hotels/Hilton Astana.webp',
		description: {
			ru: 'Ультрасовременный пятизвёздочный отель в комплексе EXPO с панорамными видами и развитой инфраструктурой.',
			kk: 'EXPO кешеніндегі панорамалық көріністері мен дамыған инфрақұрылымы бар ультразаманауи бес жұлдызды қонақүй.',
			en: 'An ultra-modern five-star hotel in the EXPO district with panoramic views and extensive amenities.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/hilton-astana.ru.html',
	},
	{
		id: 6,
		title: { ru: 'Sheraton Astana', kk: 'Sheraton Astana', en: 'Sheraton Astana' },
		slug: 'sheraton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 70000,
		currency: 'KZT',
		image: '/imgs/hotels/Sheraton Astana.webp',
		description: {
			ru: 'Sheraton Astana Hotel – премиальный отель в центре столицы с комфортабельными номерами, спа-центром и развитой инфраструктурой для бизнеса и отдыха.',
			kk: 'Sheraton Astana Hotel — елорданың орталығындағы жайлы бөлмелері, спа-орталығы және бизнес пен демалысқа арналған дамыған инфрақұрылымы бар премиум қонақүй.',
			en: 'A premium hotel in the city center featuring comfortable rooms, a spa, and well-developed facilities for business and leisure.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/sheraton-nur-sultan-hotel.ru.html',
	},
	{
		id: 7,
		title: { ru: 'Park Inn by Radisson', kk: 'Park Inn by Radisson', en: 'Park Inn by Radisson' },
		slug: 'park-inn-by-radisson-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 30000,
		currency: 'KZT',
		image: '/imgs/hotels/Park Inn by Radisson.webp',
		description: {
			ru: 'Отель удобно расположен в деловом районе Астаны и предлагает отличные условия для продуктивной работы и отдыха.',
			kk: 'Қонақүй Астананың іскер ауданында ыңғайлы орналасқан және жұмыс пен демалысқа тамаша жағдай ұсынады.',
			en: 'Conveniently located in Astana’s business district, offering great conditions for work and relaxation.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/park-inn-by-radisson-astana.ru.html#map_closed',
	},
	{
		id: 8,
		title: { ru: 'Ibis Astana', kk: 'Ibis Astana', en: 'Ibis Astana' },
		slug: 'ibis-astana',
		city: 'Astana',
		rating: 3,
		priceFrom: 24000,
		currency: 'KZT',
		image: '/imgs/hotels/Ibis Astana.webp',
		description: {
			ru: 'Современный отель бизнес-класса в центре столицы, предлагающий европейский уровень сервиса по доступной цене.',
			kk: 'Елорда орталығындағы қолжетімді бағада еуропалық сервис ұсынатын заманауи бизнес-класс қонақүйі.',
			en: 'A modern business-class hotel in the city center offering European-level service at an affordable price.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/ibis-astana.ru.html',
	},
	{
		id: 9,
		title: { ru: 'Wyndham Garden Astana', kk: 'Wyndham Garden Astana', en: 'Wyndham Garden Astana' },
		slug: 'wyndham-garden-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 25000,
		currency: 'KZT',
		image: '/imgs/hotels/Wyndham Garden Astana.webp',
		description: {
			ru: 'Комфортабельный отель рядом с EXPO и аэропортом, идеально подходящий для деловых поездок и семейного отдыха.',
			kk: 'EXPO мен әуежайға жақын, іссапарлар мен отбасылық демалысқа өте қолайлы жайлы қонақүй.',
			en: 'A comfortable hotel near the EXPO area and the airport, ideal for business trips and family stays.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/wyndham-garden-astana.ru.html',
	},
	{
		id: 10,
		title: { ru: 'Alanda', kk: 'Alanda', en: 'Alanda' },
		slug: 'alanda-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 30000,
		currency: 'KZT',
		image: '/imgs/hotels/Alanda.webp',
		description: {
			ru: 'Элегантный четырехзвездочный отель с атмосферой старой Европы и безупречным сервисом в центре Астаны.',
			kk: 'Астананың орталығындағы ескі Еуропа атмосферасы мен мінсіз сервисі бар сәнді төрт жұлдызды қонақүй.',
			en: 'An elegant four-star hotel in central Astana with an Old Europe ambiance and impeccable service.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/alanda.ru.html#map_closed',
	},
	{
		id: 11,
		title: { ru: 'The St. Regis Astana', kk: 'The St. Regis Astana', en: 'The St. Regis Astana' },
		slug: 'the-st-regis-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 130000,
		currency: 'KZT',
		image: '/imgs/hotels/The St. Regis Astana.webp',
		description: {
			ru: 'Пятизвёздочный отель премиум-класса на набережной с акцентом на эксклюзивный сервис и приватность.',
			kk: 'Жағалауда орналасқан, эксклюзивті сервис пен құпиялыққа басымдық беретін премиум санаттағы бес жұлдызды қонақүй.',
			en: 'A premium five-star waterfront hotel focused on exclusive service and privacy.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.marriott.com/en-us/hotels/tsexr-the-st-regis-astana/overview/?msockid=30a398d1273968911ba08e5426ed69a5',
	},
	{
		id: 12,
		title: { ru: 'The Ritz-Carlton, Astana', kk: 'The Ritz-Carlton, Astana', en: 'The Ritz-Carlton, Astana' },
		slug: 'the-ritz-carlton-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 117000,
		currency: 'KZT',
		image: '/imgs/hotels/The Ritz-Carlton, Astana.webp',
		description: {
			ru: 'Роскошный пятизвёздочный отель в высотном комплексе с панорамными видами на столицу.',
			kk: 'Елордаға панорамалық көрініс ашылатын биік кешендегі сәнді бес жұлдызды қонақүй.',
			en: 'A luxurious five-star hotel in a high-rise complex with panoramic views of the capital.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/ritz-carlton-astana.ru.html',
	},
	{
		id: 13,
		title: { ru: 'THE ONE Hotel Astana', kk: 'THE ONE Hotel Astana', en: 'THE ONE Hotel Astana' },
		slug: 'the-one-hotel-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 40000,
		currency: 'KZT',
		image: '/imgs/hotels/The One Hotel Astana.webp',
		description: {
			ru: 'Современный четырёхзвёздочный отель в деловом районе, ориентированный на комфортное размещение.',
			kk: 'Іскер ауданда орналасқан, жайлы орналастыруға бағытталған заманауи төрт жұлдызды қонақүй.',
			en: 'A modern four-star hotel in the business district focused on comfortable accommodation.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/the-one-astana.ru.html',
	},
	{
		id: 14,
		title: { ru: 'The Square Hotel', kk: 'The Square Hotel', en: 'The Square Hotel' },
		slug: 'the-square-hotel-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 23000,
		currency: 'KZT',
		image: 'https://visitastana.kz/upload/iblock/df8/4gook79od4oqilw7sz50xftoy5s7aulr.jpg',
		description: {
			ru: 'Городской четырёхзвёздочный отель с функциональными номерами и возможностями для мероприятий.',
			kk: 'Функционалды бөлмелері және іс-шараларға арналған мүмкіндіктері бар қалалық төрт жұлдызды қонақүй.',
			en: 'A four-star city hotel with functional rooms and facilities for events.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/the-square.ru.html',
	},
	{
		id: 15,
		title: { ru: 'Monaco', kk: 'Monaco', en: 'Monaco' },
		slug: 'monaco-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 17000,
		currency: 'KZT',
		image: '/imgs/hotels/Monaco.webp',
		description: {
			ru: 'Современный бутик-отель бизнес-класса в элитном районе Астаны, предлагающий уютные номера и высокий уровень комфорта.',
			kk: 'Астананың элиталы ауданындағы жайлы бөлмелері мен жоғары жайлылық деңгейін ұсынатын заманауи бизнес-класс бутик-қонақүй.',
			en: 'A modern business-class boutique hotel in an upscale area of Astana, offering cozy rooms and a high level of comfort.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/monaco.ru.html',
	},
	{
		id: 16,
		title: { ru: 'Ramada by Wyndham Astana', kk: 'Ramada by Wyndham Astana', en: 'Ramada by Wyndham Astana' },
		slug: 'ramada-by-wyndham-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 40000,
		currency: 'KZT',
		image: '/imgs/hotels/Ramada by Wyndham Astana.webp',
		description: {
			ru: 'Исторический отель в центре города с современными удобствами, расположенный вблизи главных коммерческих и правительственных объектов.',
			kk: 'Қала орталығындағы заманауи қолайлылықтары бар тарихи қонақүй, негізгі коммерциялық және мемлекеттік нысандарға жақын орналасқан.',
			en: 'A historic hotel in the city center with modern amenities, located close to key commercial and government venues.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/grand-park-esil.ru.html',
	},
	{
		id: 17,
		title: {
			ru: 'Hampton by Hilton Astana Triumphal Arch',
			kk: 'Hampton by Hilton Astana Triumphal Arch',
			en: 'Hampton by Hilton Astana Triumphal Arch',
		},
		slug: 'hampton-by-hilton-astana-triumphal-arch',
		city: 'Astana',
		rating: 3,
		priceFrom: 35000,
		currency: 'KZT',
		image: '/imgs/hotels/Hampton by Hilton Astana Triumphal Arch.webp',
		description: {
			ru: 'Современный отель на проспекте Мангилик Ел, предлагающий комфортные номера и удобный доступ к главным достопримечательностям нового центра столицы.',
			kk: 'Мәңгілік Ел даңғылындағы заманауи қонақүй: жайлы бөлмелер және елорданың жаңа орталығының басты көрнекі орындарына ыңғайлы қолжетімділік.',
			en: 'A modern hotel on Mangilik El Avenue offering comfortable rooms and easy access to key attractions in the new city center.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/hampton-by-hilton-astana-triumphal-arch.ru.html',
	},
	{
		id: 18,
		title: { ru: 'Beijing Palace Soluxe Hotel Astana', kk: 'Beijing Palace Soluxe Hotel Astana', en: 'Beijing Palace Soluxe Hotel Astana' },
		slug: 'beijing-palace-soluxe-hotel-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 45000,
		currency: 'KZT',
		image: 'https://visitastana.kz/upload/iblock/32a/zplmg418ml5f30p8dv9w5njqja4q2ezo.webp',
		description: {
			ru: 'Пятизвездочный отель в китайском стиле в центре левобережья, предлагающий гостям восточное гостеприимство и широкий спектр услуг.',
			kk: 'Сол жағалаудың орталығындағы қытай стиліндегі бес жұлдызды қонақүй: шығыс қонақжайлығы мен қызметтердің кең таңдауы.',
			en: 'A five-star Chinese-style hotel in the left-bank center, offering Eastern hospitality and a wide range of services.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/searchresults.ru.html?aid=315714&label=beijing-palace-soluxe-astana-piekin-palas-solaks-otiel-astana-ul8R16o4%2ARbAGeqMJmBomwS630482364160%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atikwd-43783186896%3Alp1009806%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9YROH_CMrg4mphqhBewukT84&gclid=CjwKCAjwtqmwBhBVEiwAL-WAYRctPxixf7OMu9vWDWD4o5U4Nh0DF_aZyDb--rXII7cyy3w7DRxtYhoC82YQAvD_BwE&highlighted_hotels=301434&redirected=1&city=-2334218&hlrd=no_dates&source=hotel&expand_sb=1&keep_landing=1&sid=07fea4ecee4d2e6a28ac159eb534d5c4',
	},
	{
		id: 19,
		title: { ru: 'Aisha Bibi Hotel & Spa', kk: 'Aisha Bibi Hotel & Spa', en: 'Aisha Bibi Hotel & Spa' },
		slug: 'aisha-bibi-hotel-and-spa-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 50000,
		currency: 'KZT',
		image: '/imgs/hotels/Aisha Bibi Hotel & Spa.webp',
		description: {
			ru: 'Стильный и уютный отель с высоким уровнем сервиса, расположенный в удобном районе недалеко от делового центра.',
			kk: 'Іскерлік орталыққа жақын, ыңғайлы ауданда орналасқан, сервистің жоғары деңгейі бар сәнді әрі жайлы қонақүй.',
			en: 'A stylish and cozy hotel with a high level of service, located in a convenient area near the business center.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/aisha-bibi-amp-apartments.ru.html?aid=315714&label=aisha-bibi-amp-apartments-iaY0Bz1ajEGxvEhZjfEcDwS442465497597%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atikwd-1312926160267%3Alp9196137%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9YQB9rNbOPxnnhY6p2cOLx0E&sid=b9537e9e5a8804b99e3ad0454fedb654&dest_id=-2334218&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1760509788&srpvid=f9b92da9200201e6&type=total&ucfs=1&',
	},
	{
		id: 20,
		title: { ru: 'The Veil Hotel', kk: 'The Veil Hotel', en: 'The Veil Hotel' },
		slug: 'the-veil-hotel-astana',
		city: 'Astana',
		rating: 5,
		priceFrom: 100000,
		currency: 'KZT',
		image: 'https://visitastana.kz/upload/iblock/a5b/zcfqb5rth39q747v5n71ewn3s4wm8h6p.jpg',
		description: {
			ru: 'Дизайнерский бутик-отель премиум-класса с уникальной архитектурой, изысканной кухней и роскошным спа-комплексом.',
			kk: 'Бірегей сәулеті, таңдаулы асханасы және сәнді спа-кешені бар премиум санаттағы дизайнерлік бутик-қонақүй.',
			en: 'A premium designer boutique hotel with unique architecture, fine dining, and a luxurious spa complex.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/the-veil.ru.html?aid=318615&label=New_Russian_RU_KZ_21462699985-4LmP_FEmxd3QvSD27QYXKAS217246569525%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atidsa-162439809865%3Alp9196137%3Ali%3Adec%3Adm&sid=b9537e9e5a8804b99e3ad0454fedb654&dest_id=-2334218&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1761220508&srpvid=b93953c59cfc0198&type=total&ucfs=1&',
	},
	{
		id: 21,
		title: { ru: 'Diplomat', kk: 'Diplomat', en: 'Diplomat' },
		slug: 'diplomat-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 40000,
		currency: 'KZT',
		image: 'https://visitastana.kz/upload/iblock/87c/u5oje6yjtodfwxtdo3lafmpbhjhj9tnp.jpg',
		description: {
			ru: 'Отель с панорамными видами в центре города, расположенный в шаговой доступности от основных государственных учреждений и монумента Байтерек.',
			kk: 'Қала орталығындағы панорамалық көріністері бар қонақүй: негізгі мемлекеттік мекемелер мен Бәйтерек монументіне жаяу жетуге болады.',
			en: 'A centrally located hotel with panoramic views, within walking distance of key government buildings and the Baiterek monument.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/diplomat-business-center.ru.html?aid=318615&label=New_Russian_RU_KZ_21462699985-4LmP_FEmxd3QvSD27QYXKAS217246569525%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap%3Aneg%3Afi55321457223%3Atidsa-385981318957%3Alp9196137%3Ali%3Adec%3Adm&sid=b9537e9e5a8804b99e3ad0454fedb654&dest_id=-2334218&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1762428630&srpvid=00c550e7c23c05dc&type=total&ucfs=1&',
	},
	{
		id: 22,
		title: { ru: 'Comfort Hotel', kk: 'Comfort Hotel', en: 'Comfort Hotel' },
		slug: 'comfort-hotel-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 12000,
		currency: 'KZT',
		image: '/imgs/hotels/Comfort Hotel.webp',
		description: {
			ru: 'Уютный отель в центре города с полным спектром услуг для комфортного проживания, включая спа-центр и конференц-залы.',
			kk: 'Қала орталығындағы жайлы қонақүй: спа-орталық пен конференц-залдарды қоса алғанда, жайлы тұруға арналған толық қызметтер.',
			en: 'A cozy city-center hotel with a full range of services for a comfortable stay, including a spa and conference rooms.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/comfort.ru.html?aid=356980&label=gog235jc-10CAsogAFCB2NvbWZvcnRIIVgDaIABiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuAK3nLLIBsACAdICJGM3MTdhZjkwLTRmOGMtNDcxOC1iNGRkLWMxZDMyZmUyZmFmOdgCAeACAQ&sid=b9537e9e5a8804b99e3ad0454fedb654&dest_id=-2334218&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1762430523&srpvid=6f6c549cca3b015c&type=total&ucfs=1&',
	},
	{
		id: 23,
		title: { ru: 'KazZhol Astana', kk: 'KazZhol Astana', en: 'KazZhol Astana' },
		slug: 'kazzhol-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 40000,
		currency: 'KZT',
		image: 'https://visitastana.kz/upload/iblock/e33/o0hjmjo4i7qkr37cqnj1gftn8zq2d2kl.jpg',
		description: {
			ru: 'Удобно расположенный отель с комфортными условиями для краткосрочного и длительного проживания, находящийся между правым и левым берегом.',
			kk: 'Оң және сол жағалаудың арасында орналасқан, қысқа және ұзақ мерзімге жайлы тұруға қолайлы қонақүй.',
			en: 'A conveniently located hotel between the right and left banks, offering comfortable conditions for short and long stays.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/kazschol.ru.html?aid=315714&label=kazschol-6xlpJHby0AxvVQRIxxF8QwS438042982242%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atikwd-46891826893%3Alp9196137%3Ali%3Adec%3Dm&sid=b9537e9e5a8804b99e3ad0454fedb654&all_sr_blocks=39620101_89086333_2_41_0&checkin=2025-11-07&checkout=2025-11-08&dest_id=-2334218&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&highlighted_blocks=39620101_89086333_2_41_0&hpos=1&matching_block_id=39620101_89086333_2_41_0&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&sr_pri_blocks=39620101_89086333_2_41_0__4512500&srepoch=1762489782&srpvid=6a7f1f99094200d0&type=total&ucfs=1&',
	},
	{
		id: 24,
		title: { ru: 'Traditional', kk: 'Traditional', en: 'Traditional' },
		slug: 'traditional-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 50000,
		currency: 'KZT',
		image: 'https://visitastana.kz/upload/iblock/385/ejz0rtjzpefl826a7a7v25kptkht8rwh.jpg',
		description: {
			ru: 'Гостинично-ресторанный комплекс в классическом стиле с роскошными интерьерами, сауной и рестораном славянской кухни.',
			kk: 'Классикалық стильдегі қонақүй-мейрамхана кешені: сәнді интерьерлер, сауна және славян асханасының мейрамханасы.',
			en: 'A classic-style hotel and restaurant complex with luxurious interiors, a sauna, and a Slavic-cuisine restaurant.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/traditional.ru.html?aid=356980&label=gog235jc-10CAsogAFCC3RyYWRpdGlvbmFsSCFYA2iAAYgBAZgBM7gBF8gBDNgBA-gBAfgBAYgCAagCAbgCl4m2yAbAAgHSAiRlMGM5MGJlMi01YzRhLTQ4YjctOTRiZi1mMTM3MjY2MzM2MjXYAgHgAgE&sid=b9537e9e5a8804b99e3ad0454fedb654&age=0&checkin=2025-11-07&checkout=2025-11-08&dest_id=-2334218&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&soh=1&sr_order=popularity&srepoch=1762493621&srpvid=af30270ccfcd010d&type=total&ucfs=1&#no_availability_msg',
	},
	{
		id: 25,
		title: { ru: 'Jumbaktas', kk: 'Jumbaktas', en: 'Jumbaktas' },
		slug: 'jumbaktas-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 50000,
		currency: 'KZT',
		image: '/imgs/hotels/Jumbaktas.webp',
		description: {
			ru: 'Комфортабельный отель на левом берегу с панорамными видами и широким выбором номеров от стандарта до президентских апартаментов.',
			kk: 'Сол жағалаудағы панорамалық көріністері бар жайлы қонақүй: стандарттан президенттік апартаменттерге дейінгі бөлмелер таңдауы кең.',
			en: 'A comfortable left-bank hotel with panoramic views and a wide range of rooms, from standard to presidential suites.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/jumbaktas.ru.html?label=gog235jc-10CAsogAFCCWp1bWJha3Rhc0ghWANogAGIAQGYATO4ARfIAQzYAQPoAQH4AQGIAgGoAgG4ApWYtsgGwAIB0gIkYThiYTZhMWItYzIyMi00NTU1LTliNjktNzU5YmNmM2FlZTE42AIB4AIB&sid=b9537e9e5a8804b99e3ad0454fedb654&aid=356980&ucfs=1&arphpl=1&checkin=2025-11-07&checkout=2025-11-08&dest_id=-2334218&dest_type=city&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=1&hapos=1&sr_order=popularity&srpvid=d3492acbcfb00e12&srepoch=1762495515&all_sr_blocks=0_0_2_1_0&highlighted_blocks=0_0_2_1_0&matching_block_id=0_0_2_1_0&sr_pri_blocks=0_0_2_1_0__4355675&from=searchresults',
	},
	{
		id: 26,
		title: { ru: 'Best Western Plus Astana', kk: 'Best Western Plus Astana', en: 'Best Western Plus Astana' },
		slug: 'best-western-plus-astana',
		city: 'Astana',
		rating: 4,
		priceFrom: 50000,
		currency: 'KZT',
		image: '/imgs/hotels/Best Western Plus Astana.webp',
		description: {
			ru: 'Современный отель мирового бренда в центре столицы, ориентированный на деловых путешественников и туристов.',
			kk: 'Елорда орталығындағы әлемдік брендтің заманауи қонақүйі, іссапардағы қонақтар мен туристерге бағытталған.',
			en: 'A modern global-brand hotel in the city center, designed for business travelers and tourists.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/best-western-plus-astana.ru.html?aid=356980&label=gog235jc-10CAsogAFCGGJlc3Qtd2VzdGVybi1wbHVzLWFzdGFuYUghWANogAGIAQGYATO4ARfIAQzYAQPoAQH4AQGIAgGoAgG4AsultsgGwAIB0gIkYzllZmFlZDItNDIyMS00YzVjLWI3N2UtZTU5MmNiNmQxMWRl2AIB4AIB&sid=b9537e9e5a8804b99e3ad0454fedb654&age=0&all_sr_blocks=0_0_2_1_0&checkin=2025-11-07&checkout=2025-11-08&dest_id=-2334218&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&highlighted_blocks=0_0_2_1_0&hpos=1&matching_block_id=0_0_2_1_0&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&sr_pri_blocks=0_0_2_1_0__4512046&srepoch=1762497232&srpvid=29062e26db12056a&type=total&ucfs=1&',
	},
	{
		id: 27,
		title: { ru: 'Rixos Borovoe', kk: 'Rixos Borovoe', en: 'Rixos Borovoe' },
		slug: 'rixos-borovoe',
		city: 'Astana',
		rating: 5,
		priceFrom: 100000,
		currency: 'KZT',
		image: '/imgs/hotels/Rixos Borovoe.webp',
		description: {
			ru: 'Роскошный курортный отель на берегу озера Щучье в окружении соснового леса, предлагающий исключительный сервис и спа-отдых.',
			kk: 'Шортанды көлі жағасында, қарағайлы орман қоршауындағы сәнді курорттық қонақүй: ерекше сервис және спа-демалыс.',
			en: 'A luxury resort on the shore of Lake Shchuchye, surrounded by pine forest, offering exceptional service and spa relaxation.',
		},
		buttonText: { ru: 'Забронировать', kk: 'Брондау', en: 'Book' },
		link: 'https://www.booking.com/hotel/kz/rixos-borovoe.ru.html',
	},
]

export function getHotels(locale: Locale = 'ru') {
	return hotelsMultilang.map((hotel) => ({
		id: hotel.id,
		slug: hotel.slug,
		rating: hotel.rating,
		priceFrom: hotel.priceFrom,
		currency: hotel.currency,
		image: hotel.image,
		description: hotel.description[locale],
		link: hotel.link,
		title: hotel.title[locale],
		city: hotel.city,
		buttonText: hotel.buttonText[locale],
	}))
}
